=== legislation/legislation-bho-to-clml/data/dtd/bho/index.dtd
<!ELEMENT index (title, subtitle, (intro|section|entry|page|note)*)>
<!ATTLIST index id CDATA #REQUIRED>
<!ATTLIST index pubid CDATA #REQUIRED>
<!ATTLIST index publish CDATA #IMPLIED>
<!--         publish (false|true) "true"> -->

<!-- Sarah and Jonathan made head non-mandatory to allow for para comments that are not part of the first letter of an index entry-->
<!ELEMENT section ((head|para|section|entry|page|note)*)>
<!ATTLIST section id CDATA #REQUIRED>

<!ELEMENT entry (head|sub|page|table)*>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT intro (#PCDATA|emph|para|table)*>
<!ELEMENT para (#PCDATA|emph|br)*>
<!ATTLIST para id CDATA #REQUIRED>
<!ELEMENT head (#PCDATA|key|emph|addenda|ref|page|plt)*>
<!ELEMENT key (#PCDATA|emph|addenda|ref)*>
<!ELEMENT sub (#PCDATA|emph|sub|page|addenda|ref|plt)*>
<!ELEMENT emph (#PCDATA|emph)*>
<!ATTLIST emph type (b|i|p|c|d) #REQUIRED>
<!ELEMENT br EMPTY>

<!-- page added Jan 25th 2007 -->
<!ELEMENT page EMPTY>
<!ATTLIST page start CDATA #REQUIRED>

<!-- English Heritage only-->
<!ELEMENT plt (#PCDATA)>
<!ATTLIST plt target CDATA #REQUIRED>

<!-- Addenda added Nov 24th 2005 for Survey of London -->
<!ELEMENT addenda (#PCDATA|emph)*>
<!ATTLIST entry type (addenda) #IMPLIED>

<!-- table copied in from report June 5th, 2006 for Statutes of the Realm-->
<!ELEMENT table (head?,(tr|page)+)>
<!ATTLIST table 
         id CDATA #REQUIRED
         caption CDATA #IMPLIED
         number CDATA #IMPLIED>
<!ELEMENT tr (th|td)*>
<!ATTLIST th
         cols CDATA #IMPLIED
         rows CDATA #IMPLIED>
<!ATTLIST td
         cols CDATA #IMPLIED
         rows CDATA #IMPLIED>
<!ELEMENT th (#PCDATA|ref|emph|br)*>
<!ELEMENT td (#PCDATA|ref|emph|br|page)*>


<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref idref IDREF #IMPLIED>
<!ATTLIST ref type (footnote|reference|addenda) "footnote">

<!ELEMENT note (#PCDATA|ref|emph|br|table)*>
<!ATTLIST note 
         id ID #REQUIRED
         number CDATA #REQUIRED
         type (footnote|reference|addenda) "footnote">



<!ENTITY % ent-isoamsa SYSTEM "isoamsa.ent">
%ent-isoamsa;
<!ENTITY % ent-isoamsb SYSTEM "isoamsb.ent">
%ent-isoamsb;
<!ENTITY % ent-isoamsc SYSTEM "isoamsc.ent">
%ent-isoamsc;
<!ENTITY % ent-isoamsn SYSTEM "isoamsn.ent">
%ent-isoamsn;
<!ENTITY % ent-isoamso SYSTEM "isoamso.ent">
%ent-isoamso;
<!ENTITY % ent-isoamsr SYSTEM "isoamsr.ent">
%ent-isoamsr;
<!ENTITY % ent-isobox SYSTEM "isobox.ent">
%ent-isobox;
<!ENTITY % ent-isocyr1 SYSTEM "isocyr1.ent">
%ent-isocyr1;
<!ENTITY % ent-isocyr2 SYSTEM "isocyr2.ent">
%ent-isocyr2;
<!ENTITY % ent-isodia SYSTEM "isodia.ent">
%ent-isodia;
<!ENTITY % ent-isogrk1 SYSTEM "isogrk1.ent">
%ent-isogrk1;
<!ENTITY % ent-isogrk2 SYSTEM "isogrk2.ent">
%ent-isogrk2;
<!ENTITY % ent-isogrk3 SYSTEM "isogrk3.ent">
%ent-isogrk3;
<!ENTITY % ent-isogrk4 SYSTEM "isogrk4.ent">
%ent-isogrk4;
<!ENTITY % ent-isolat1 SYSTEM "isolat1.ent">
%ent-isolat1;
<!ENTITY % ent-isolat2 SYSTEM "isolat2.ent">
%ent-isolat2;
<!ENTITY % ent-isonum SYSTEM "isonum.ent">
%ent-isonum;
<!ENTITY % ent-isopub SYSTEM "isopub.ent">
%ent-isopub;
<!ENTITY % ent-isotech SYSTEM "isotech.ent">
%ent-isotech;

<!ENTITY % ent-bhoa SYSTEM "bhoa.ent">
%ent-bhoa;

=== legislation/legislation-bho-to-clml/data/pubid-352/46451.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE index SYSTEM "../dtd/index.dtd">
<index id="46451" pubid="352">
<title>Index</title>
<subtitle>M</subtitle>

<entry><head><key>Mace</key> <emph type="i">See</emph> Importation.</head></entry>
<entry><head><key>Marriages</key>, Births, Burials, Bachelors, and Widowers</head>
<table id="t1">
				<tr>
					<td cols="3"/>
				</tr>
				<tr>
				 <td/>
					<td>Statute</td>
					<td>Page</td>
				</tr>
				<tr>
					<td>For granting certain Duties upon, for the Term of Five Years, for carrying on the War with France with Vigour.<br/>
					<emph type="i">Duties continued until</emph> 1<emph type="i">st August</emph> 1706, 8 &amp; 9 <emph type="i">W.III.c</emph>. 20. &sect; 14. <emph type="i">and the Powers of this Act relating to the Duties to be executed</emph> 9 &amp; 10 <emph type="i">W.III.c</emph>. 35. &sect; 1. <emph type="i">but now expired</emph>.</td>
					<td>6 &amp; 7 <emph type="i">W</emph>. &amp; <emph type="i">M. c</emph>. 6. <emph type="i">exp</emph>.</td>
					<td>568</td>
				</tr>
				<tr>
					<td>Persons in Holy Orders to keep a Register of Marriages, Christenings, and Burials.<br/>
					<emph type="i">Indemnity to Persons, in certain Cases, for not having kept Register</emph>, 4 <emph type="i">Ann. c</emph>.12. &sect; 10.<br/>
					<emph type="i">As to preserving Registers, see</emph> 52 <emph type="i">G.III.c</emph>.146.</td>
					<td>&sect; 20.</td>
					<td>577</td>
				</tr>
			 <tr>
					<td>Parson, &amp;c. marrying Persons in Places pretending to be exempt from Visitation, without a License, unless Banns published&mdash;First Offence, Penalty &pound;100; Second Offence, Suspension for Three Years.<br/>
					<emph type="i">Extended to Places not exempt</emph>, &amp; <emph type="i">c</emph>. 7 &amp; 8 <emph type="i">W.III.c</emph>. 35. &sect; 2. <emph type="i">and see</emph> &sect; 5. 6. <emph type="i">of that Act</emph>.</td>
					<td>&sect; 47.</td>
					<td>581</td>
				</tr>
		 </table></entry>
			<entry><head><key>Master of the Crown Office</key> <emph type="i">See</emph> Court of King's Bench. Crown Office.</head></entry>
			<entry><head><key>Measuring of Ships</key> <emph type="i">See</emph> Connage of Ships.</head></entry>
			<entry><head><key>Metal made of English Dre only</key> <emph type="i">See</emph> Exportation.</head></entry>
			<entry><head><key>Militia and Crained Bands</key></head>
<table id="t2">
				<tr>
					<td cols="3"/>
				</tr>
				<tr>
				<td/>
				<td>Pages</td>
				</tr>
				<tr>
					<td>Statutes, 2 W. &amp; M. Sess. 2. c.12.</td>
					<td>246</td>
				</tr>
				<tr>
					<td>3 W. &amp; M.c.7.</td>
					<td>310</td>
				</tr>
				<tr>
					<td>4 W. &amp; M.c.6.</td>
					<td>387</td>
				</tr>
				<tr>
					<td>5 &amp; 6 W. &amp; M. c. 19.</td>
					<td>482</td>
				</tr>
				<tr>
					<td>6 &amp; 7 W. &amp; M. c. 13.<br/>
					<emph type="i">See</emph> Commission and Warrant Officers in their Majesties Service by Land.</td>
					<td>594</td>
				</tr>
			</table></entry>
			<entry><head><key>Mines</key></head>
<table id="t3">
				<tr>
					<td cols="3"/>
				</tr>
				<tr>
				 <td/>
					<td>Statute</td>
					<td>Page</td>
				</tr>
				<tr>
					<td>To prevent Disputes and Controversies concerning Royal Mines.</td>
					<td>5 <emph type="i">W</emph>. &amp; <emph type="i">M. c</emph>. 6.</td>
					<td>446</td>
				</tr>
				<tr>
					<td>Owners of Lead, &amp;c. Mines, to enjoy them, notwithstanding Claim of Royal Mine.</td>
					<td>&sect; 1.</td>
					<td>
						<emph type="i">Ib</emph>.</td>
				</tr>
				<tr>
					<td>King to have the Ore (Exception) at a Rate. Several Rates.<br/>
					<emph type="i">The Rate altered</emph>, 55 <emph type="i">G. III.c</emph>. 134.</td>
					<td>&sect; 2.</td>
					<td>
						<emph type="i">Ib</emph>.</td>
				</tr>
				<tr>
					<td>Proviso for Charters, &amp;c. to Tinners of Devon and Cornwall.<br/>
					<emph type="i">See</emph> Multiplying Gold and Silver.</td>
					<td>&sect; 3.</td>
					<td>447</td>
				</tr>
			</table></entry>
<entry><head><key>Molasses</key> <emph type="i">See</emph> Ercise.</head></entry>
<entry><head><key>Money</key> <emph type="i">See</emph> Coin.</head></entry>
<entry><head><key>Monmouth</key>, Duke of</head>
 <table id="t4">
 <tr>
 <td cols="3"/>
 </tr>
 <tr>
 <td/>
					<td>Statute</td>
					<td>Page</td>
 </tr> 	
 <tr>
 <td>Attainted of High Treason.</td><td>1 <emph type="i">Jac. II. c</emph>. 2.</td>
 <td>2</td>
 </tr>
 </table></entry>
<entry><head><key>Mortgages</key>.</head>
			<table id="t5">
				<tr>
					<td cols="3"/>
				</tr>
				<tr>
				 <td/>
					<td>Statute</td>
					<td>Page</td>
				</tr>
				<tr>
					<td>For preventing Frauds by clandestine Mortgages.</td>
					<td>4 <emph type="i">W</emph>. &amp; <emph type="i">M. c</emph>. 16.</td>
					<td>404</td>
				</tr>
				<tr>
					<td>Debtor upon Judgment, &amp;c. taking up Money of another upon Mortgage, without giving Notice of the Judgment to the Mortgagee, unless, upon Notice by the Mortgagee, he pay off the same within 6 months, shall lose his Equity of Redemption, and Mortgagee may hold the Land against such Mortgagor for such Estate as was granted to him, freed from Equity of Redemption.</td>
					<td>&sect; 1.</td>
					<td>
						<emph type="i">Ib</emph>.</td>
				</tr>
				<tr>
					<td>Persons having mortgaged and mortgaging again without giving Notice to the Second or other succeeding Mortgagee, to lose his Equity of Redemption, and such Mortgagee may in like manner hold the Land.</td>
					<td>&sect; 2.</td>
					<td>405</td>
				</tr>
				<tr>
					<td>Under-Mortgagees may redeem.</td>
					<td>&sect; 3.</td>
					<td>
						<emph type="i">Ib</emph>.</td>
				</tr>
				<tr>
					<td>Proviso for Dower.</td>
					<td>&sect; 4.</td>
					<td>
						<emph type="i">Ib</emph>.</td>
				</tr>
			</table></entry>
<entry><head><key>Multiplying Gold and Silber</key></head>
<table id="t6">
				<tr>
					<td cols="3"/>
				</tr>
				<tr>
 <td/>
 <td>Statute</td>
 <td>Page</td>
 </tr>
				<tr>
					<td>Statute 5 H. IV. c. 4. repealed.</td>
					<td>1 <emph type="i">W</emph>. &amp; <emph type="i">M. c</emph>.30. &sect; 1.</td>
					<td>95</td>
				</tr>
				<tr>
					<td>Condition of Repeal.</td>
					<td>&sect; 2.</td>
					<td>
						<emph type="i">Ib</emph>.</td>
				</tr>
				<tr>
					<td>Mines of Copper, Tin, Iron, or Lead not to be adjudged Royal Mines, though Gold or Silver extracted out of the same.<br/>
					<emph type="i">This Section explained</emph>, 5&amp; 6 <emph type="i">W</emph>. &amp; <emph type="i">M. c</emph>. 6.</td>
					<td>&sect; 3.</td>
					<td>
						<emph type="i">Ib</emph>.</td>
				</tr>
				</table></entry>
				<entry><head><key>Mum</key> <emph type="i">See</emph> Excise.</head></entry>
				<entry><head><key>Mundick Metal</key> <emph type="i">See</emph> Exportation.</head></entry>
				<entry><head><key>Mutiny and Desertion.</key></head>
				<table id="t7">
				<tr>
					<td cols="3"/>
				</tr>
				<tr>
				 <td/>
					<td>Statute</td>
					<td>Page</td>
				</tr>
				<tr>
					<td rows="4">For punishing Officers and Soldiers who shall mutiny or desert their Majesties Service.</td>
					<td>1<emph type="i">W</emph>. &amp; <emph type="i">M. c</emph>. 5.</td>
					<td>55</td>
				</tr>
				<tr>
					<td>
						<emph type="i">Sess</emph>.2. <emph type="i">c</emph>.4.</td>
					<td>146</td>
				</tr>
				<tr>
					<td>2 <emph type="i">W</emph>. &amp; <emph type="i">M. Sess</emph>.2. <emph type="i">c</emph>.6.</td>
					<td>227</td>
				</tr>
				<tr>
					<td>4 <emph type="i">W</emph>. &amp; <emph type="i">M.c</emph>. 13.</td>
					<td>393</td>
				</tr>
				<tr>
					<td rows="2">Statutes 4 W. &amp; M. c. 13.&mdash;5 &amp; 6 W. &amp; M.c. 15. continued until 10th April 1796.</td>
					<td>5 &amp; 6 <emph type="i">W</emph>.&amp; <emph type="i">M. c</emph>.15.</td>
					<td>479</td>
				</tr>
				<tr>
					<td>6 &amp; 7 <emph type="i">W</emph>. &amp; <emph type="i">M. c</emph>. 8. &sect; 1,2.</td>
					<td>587</td>
				</tr>
			</table></entry>
</index>

=== legislation/legislation-bho-to-clml/data/pubid-353/47015.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE index SYSTEM "../dtd/index.dtd">
<index id="47015" pubid="353" publish="true">
	<title>Index</title>
	<subtitle>K</subtitle>
<section id="s1"><head>K.</head>
	<entry>
		<head>
			<key>The King</key>
		</head>
		<table id="t1">
			<tr>
				<td cols="3"/>
			</tr>
			<tr>
				<td/>
				<th>Statute</th>
				<th>Page</th>
				</tr>
<tr>
<td>For empowering His Majesty to apprehend and detain such Persons as he shall find Cause to suspect are conspiring against His Royal Person or Government.</td>
				<td>7 &amp; 8 <emph type="i">W. III. c</emph>. 11.</td>
				<td>74</td>
				</tr>				
<tr><td>Persons in Prison 20th Feb. 1695, or after, on Suspicion of Treason, &amp;c. may be detained until 1st Sept. 1696; and no Judge to bail without Order from the Privy Council.</td>
				<td>&sect; 1.</td>
				<td><emph type="i">Ib</emph>.</td>
				</tr>				
<tr><td>Persons so committed to have the Benefit of Stat. 31 Car. II. c. 2., and of all other Laws for the Liberty of the Subject.</td>
				<td>&sect; 2.</td>
				<td><emph type="i">Ib</emph>.</td>
				</tr>
<tr><td>Proviso for Privileges of Parliament.</td>
				<td>&sect; 3.</td>
				<td><emph type="i">Ib</emph>.</td>
				</tr>				
<tr><td>Lieutenants of Counties, and their Deputies, may, by Warrant under Hand and Seal, employ Persons to search for and seize and detain Horses of &pound;5 Value and upwards belonging to suspected Persons&mdash;And Owner liable to Innkeeper for Keep of such Horses, at a Rate herein mentioned.</td>
				<td>&sect; 4.</td>
				<td><emph type="i">Ib</emph>.</td>
				</tr>
<tr><td>Hours at which such Search may be made.</td>
				<td><emph type="i">Ib</emph>.</td>
				<td>
					<emph type="i">Ib</emph>.</td></tr>
<tr><td>In case of Resistance Persons may enter by Force, and Horses may be used in case of Invasion, &amp;c.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
				<td>
					<emph type="i">Ib</emph>.</td></tr>
<tr><td>Proviso as to Breeding Mares.</td>
				<td>&sect; 5.</td>
				<td>
					<emph type="i">Ib</emph>.</td></tr>
<tr><td>For the better Security of His Majesty's Royal Person and Government.</td>
				<td>7 &amp; 8 <emph type="i">W. III. c</emph>. 27.</td>
				<td>114</td>
				</tr>
<tr><td>Refusing to take the Oaths of Stat. 1 W. &amp; M. c. 8., or to appear to have the said Oaths tendered to them &mdash;Penalty.</td>
				<td>&sect; 1.</td>
				<td>
					<emph type="i">Ib</emph>.</td></tr>
<tr><td>Persons tendering Oaths to record the Names, &amp;c. of Persons refusing to take them, or not appearing to certify the same to Justices of Assize, &amp;c. who are to estreat, and certify into Court of Exchequer.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
				<td>
					<emph type="i">Ib</emph>.</td></tr>
<tr><td>Publishing, &amp;c. that His Majesty is not rightful King, or that the late King James or the pretended Prince of Wales hath any Right to the Crown, &amp;c.&mdash; Premunire, Stat. 16 R. II. c. 5.</td>
				<td>&sect; 2.</td>
				<td>
					<emph type="i">Ib</emph>.</td></tr>
<tr><td>Recital of the Association. <br/><emph type="i">Form of Association altered, see</emph> 13 &amp; 14 <emph type="i">W. III. c</emph>. 6. &sect; 16. <emph type="i">Determined</emph>, 1 <emph type="i">Ann.stat</emph>. 1. c. 22. &sect; 3.</td>
				<td>&sect; 3.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
					</tr>
<tr><td>Commissioners of Public Accounts, and other Persons holding Offices under the Crown, to appear as herein mentioned, and subscribe the said Association.</td>
				<td>&sect; 4.</td>
				<td>115</td>
				</tr>
<tr><td>Persons admitted, &amp;c. into any Office, Civil or Military, or receiving Pay, &amp;c. under Patent or Grant from the Crown, &amp;c. to subscribe the said Association at the same Time that they make and subscribe the Declaration of Stat. 25 Car.II. c.2.</td>
				<td>&sect; 5.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
					</tr>
<tr><td>Persons neglecting, &amp;c. to subscribe the Association disabled.</td>
				<td>&sect; 6.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
					</tr>
<tr><td>Persons who have neglected, &amp;c. to subscribe the said Association, and yet executing Offices&mdash;Penalty.</td>
				<td>&sect; 7.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
				<tr>
				<td>Courts of Justice herein mentioned may tender the said Association for Subscription&mdash;Register of Subscription kept.</td>
				<td>7 &amp; 8 <emph type="i">W. III. c</emph>. 27. &sect; 8.</td>
				<td>115</td>
			</tr>
			<tr>
				<td>In what Case Persons who have forfeited Offices, by neglecting, &amp;c. to subscribe, may hold the same again.</td>
				<td>&sect; 9.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>Limitation of Information for Words spoken &mdash; Two Witnesses necessary to Conviction. <br/><emph type="i">As to Repeal of Sections from 3 to 10, both inclusive, see 1 Ann. stat</emph>. 1. <emph type="i">c</emph>. 22. &sect; 3.</td>
				<td>&sect; 10.</td>
				<td>116.</td>
			</tr>
				<tr>
				<td>Proviso for Quakers making and subscribing Declaration of Fidelity of Stat. 1 W. &amp; M. c. 18., and proving themselves to be Quakers.</td>
				<td>&sect; 11.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>Persons in the Service of Prince and Princess of Denmark to subscribe the said Association&mdash;Penalty.</td>
				<td>&sect; 12.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>Proviso for Persons in His Majesty's Service in the Fleet or beyond Sea.</td>
				<td>&sect; 13.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>Proviso for Pardon of Penalties, &amp;c. under the Privy Seal.</td>
				<td>&sect; 14.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>After the Determination of the present Parliament, Members taking the Oaths, &amp;c. of Stat. 1 W. &amp; M. c. 8. to subscribe the said Association.</td>
				<td>&sect; 15.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>Refusing, disabled to sit &mdash;New Writ.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>English Subjects returning from France without Leave under Sign Manual&mdash;High Treason.</td>
				<td>&sect; 16.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>English Subjects returned from France since 29th Sept. 1695, without Licence under Stat. 3 W. &amp; M. c. 13. to surrender themselves and take the Oaths of Stat. 1 W. &amp; M. c. 8., and give Security for good Behaviour; or otherwise, not having Licence to continue, to depart the Kingdom, and not return during the War with France without Licence.</td>
				<td>&sect; 17.</td>
				<td>117</td>
			</tr>
			<tr>
				<td>Refusing to surrender, &amp;c. or returning&mdash; Premunire.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>Persons refusing the Oaths of Stat. 1 W. &amp; M. c. 8., or, being Quakers, refusing to subscribe the Declaration of Fidelity of Stat. 1 W. &amp; M. c. 18, which may be administered by Sheriff, &amp;c. at Poll, not admitted to vote.</td>
				<td>&sect; 18.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>Persons committed for High Treason before the last Day of Trinity Term 1696, may be detained without Bail until 1st Dec. 1696, unless bailed by Order of Council.</td>
				<td>&sect; 19.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
			<tr>
				<td>No Commission, Civil or Military, to cease by the Demise of the King, save as herein mentioned. <br/><emph type="i">This Clause explained</emph>, 1 <emph type="i">Ann. stat</emph>. 1. <emph type="i">c</emph>. 8. &sect; 1, 2.</td>
				<td>&sect; 20.</td>
				<td>
					<emph type="i">Ib</emph>.</td>
			</tr>
				<tr>
				<td>This Act concerning the Subscription of the Association, not to make void Offices of Inheritance in Fee-Simple, so as the Persons holding such Offices appoint Deputies until such Time as the Persons having such Offices subscribe the Association, and so as such Deputies subscribe the same and be approved by the King.<br/>
				<emph type="i">See Note to</emph> &sect; 10.</td>
				<td>7 &amp; 8 <emph type="i">W.III.c</emph>. 27. &sect; 21.</td>
				<td>117</td>
			</tr>
			<tr>
				<td>For continuing the Imprisonment of Counter, and others, for the late horrid Conspiracy to assassinate the Person of His Sacred Majesty.</td>
				<td>9 <emph type="i">W.III.c</emph>.4.</td>
				<td>300</td>
			</tr>
			<tr>
				<td>Imprisonment continued until 1st Jan. 1698, &amp;c. unless bailed, &amp;c. by Order of Council.</td>
				<td>
					<emph type="i">Exp</emph>.</td>
			</tr>
			<tr>
				<td>For continuing the Imprisonment of Counter, and others, for the late Conspiracy to assassinate the Person of His Sacred Majesty.<br/><emph type="i">See</emph> Cunnage and Boundage.</td>
				<td>10 <emph type="i">W.III.c</emph>.19. <emph type="i">exp</emph>.</td>
				<td>531</td>
			</tr>
		</table>
	</entry>
	<entry>
		<head>
			<key>King's Bench Prison</key>
			<emph type="i"> See</emph> Creditors.</head>
	</entry>
</section>
</index>
