=== legislation/legislation-bho-to-clml/data/dtd/bho/report.dtd
<!ELEMENT report (title, subtitle, (page*,section*,geodata?))>
<!ATTLIST report 
         id CDATA #REQUIRED
         pubid CDATA #REQUIRED
         publish CDATA #IMPLIED>
<!--         publish (false|true) "true"> -->
<!-- added for LIWW -->
<!--! Jonathan altered some some elements' scope to account for London Inhabitants Without the Walls: name;  -->

<!ELEMENT subtitle (#PCDATA|emph|ref)*>

<!-- narrative content -->
<!ELEMENT section (head,(para|list|table|note|figure|plate|quote|section|fig|name|business|dataset|catalogue|mapset|page)*)>
<!ATTLIST section 
         id CDATA #REQUIRED
         title CDATA #IMPLIED
         type CDATA #IMPLIED>
<!ELEMENT head (#PCDATA|ref|emph|plt)*>
<!ELEMENT para (#PCDATA|ref|emph|person|glink|plt|br|page|mdr)*>
<!ATTLIST para id CDATA #REQUIRED>
<!ELEMENT person (#PCDATA)>
<!ELEMENT glink (#PCDATA)>
<!ELEMENT quote (quotext|quosource)*>
<!ATTLIST quote id ID #REQUIRED>
<!ELEMENT quotext (quoline)*>
<!ELEMENT quoline (#PCDATA|ref|emph|page)*>
<!ELEMENT quosource (#PCDATA|ref|emph)*>
<!ELEMENT emph (#PCDATA|emph|ref|page|br|mdr)*>
<!ATTLIST emph type (b|i|p|d|c|k|u) #REQUIRED>
<!ELEMENT fig (#PCDATA)>
<!ATTLIST fig idref IDREF #IMPLIED>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!-- English Heritage only-->
<!ELEMENT plt (#PCDATA)>
<!ATTLIST plt target CDATA #REQUIRED>

<!-- in text markers to footnotes-->
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref idref IDREF #IMPLIED>
<!ATTLIST ref type (footnote|reference|addenda) "footnote">

<!-- in text graphics -->
<!ELEMENT figure (title|caption)*>
<!ATTLIST figure 
         id ID #REQUIRED
         number CDATA #REQUIRED
         graphic CDATA #REQUIRED
         visible CDATA #IMPLIED>
<!-- English Heritage only-->
<!ELEMENT plate (title|caption)*>
<!ATTLIST plate 
         id ID #REQUIRED
         number CDATA #REQUIRED
         graphic CDATA #REQUIRED>

<!ELEMENT title (#PCDATA|emph|ref)*>
<!ELEMENT caption (#PCDATA|ref|emph|br)*>

<!-- footnotes, referenced using ref tag-->
<!ELEMENT note (#PCDATA|ref|emph|br|plt|figure|table|para|page)*>
<!ATTLIST note 
         id ID #REQUIRED
         number CDATA #REQUIRED
         type (footnote|reference|addenda) "footnote">

<!-- Table, dervied from html-->
<!ELEMENT table (head?,(tr|page)+)>
<!ATTLIST table 
         id CDATA #REQUIRED
         caption CDATA #IMPLIED
         number CDATA #IMPLIED>
<!ELEMENT tr (th|td)*>
<!ATTLIST tr 
         id ID #IMPLIED>



<!ELEMENT th (#PCDATA|ref|emph|br|plt)*>
<!ELEMENT td (#PCDATA|ref|emph|br|plt|page|mdr|list)*>

<!ATTLIST th
         cols CDATA #IMPLIED
         rows CDATA #IMPLIED>
<!ATTLIST td
         cols CDATA #IMPLIED
         rows CDATA #IMPLIED>
<!ELEMENT place (#PCDATA)*>
<!ATTLIST place id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA|nhead|nsub|page|ref)*>
<!ELEMENT nhead (#PCDATA|place|nkey|ref)*>
<!ELEMENT nkey (#PCDATA|ref)*>
<!ELEMENT nsub (#PCDATA|place|ref)*>

<!-- list, derived from html-->
<!ELEMENT list (head,(li|page)+)>
<!ELEMENT li (#PCDATA|page|ref|emph|br)*>
<!ATTLIST list id CDATA #REQUIRED>

<!-- in-text line break-->
<!ELEMENT br EMPTY>

<!-- new page tokens -->
<!ELEMENT page EMPTY>
<!ATTLIST page start CDATA #REQUIRED>
<!ATTLIST page pubid CDATA #IMPLIED>

<!-- CSP modern document references -->
<!ELEMENT mdr (#PCDATA)>
<!ATTLIST mdr id CDATA #REQUIRED>

<!-- depracted business directory -->
<!ELEMENT business (house,street,ward,occupier,trade, (staff*))>
<!ELEMENT house (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT ward (#PCDATA)>
<!ELEMENT occupier (#PCDATA)>
<!ELEMENT trade (#PCDATA)>
<!ELEMENT staff (#PCDATA)>

<!-- 1st generation dataset structure -->
<!ELEMENT geodata (geoclass+,geolocation+,geoitem+)>

<!ELEMENT geoclass (label,description,shortdesc,scale)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT description (#PCDATA|emph)*>
<!ELEMENT shortdesc (#PCDATA)>
<!ELEMENT scale (range)+>
<!ELEMENT range (#PCDATA)>

<!ATTLIST geoclass id ID #REQUIRED>
<!ATTLIST geoclass type (year|sterling) "year">
<!ATTLIST range id ID #REQUIRED>
<!ATTLIST range begin CDATA #REQUIRED>
<!ATTLIST range end CDATA #REQUIRED>

<!ELEMENT geolocation (#PCDATA)>
<!ATTLIST geolocation id ID #REQUIRED>
<!ATTLIST geolocation section CDATA #IMPLIED>
<!ATTLIST geolocation coordx CDATA #REQUIRED>
<!ATTLIST geolocation coordy CDATA #REQUIRED>

<!ELEMENT geoitem (#PCDATA)>
<!ATTLIST geoitem id ID #REQUIRED>
<!ATTLIST geoitem class IDREF #REQUIRED>
<!ATTLIST geoitem place IDREF #REQUIRED>



<!-- 2nd generation dataset structure -->
<!ELEMENT dataset (dsclass+,dsrecord+)>
<!ELEMENT dsclass (label,description,shortdesc?,scale?)>
<!ATTLIST dsclass id ID #REQUIRED>
<!ATTLIST dsclass type (year|sterling|text|integer|geox|geoy) "text">
<!ATTLIST dsclass sortkey CDATA #REQUIRED>
<!ATTLIST dsclass showheader (True|False) "True">
<!ATTLIST dsclass showcolumn (True|False) "True">
<!ATTLIST dsclass width CDATA #IMPLIED>
<!-- standard, that dsclass c0 in all cases should describe the main record -->
<!ELEMENT dsrecord (prop+)>
<!ATTLIST dsrecord id ID #REQUIRED>
<!ATTLIST dsrecord coordx CDATA #IMPLIED>
<!ATTLIST dsrecord coordy CDATA #IMPLIED>
<!ELEMENT prop (#PCDATA|ref|emph|br)*>
<!ATTLIST prop class IDREF #REQUIRED>



<!-- catalogue structure -->
<!ELEMENT catalogue (group+)>
<!ATTLIST catalogue classref CDATA #REQUIRED>
<!ELEMENT group (head,(item|group)*)>
<!ATTLIST group id ID #REQUIRED>
<!ELEMENT item (#PCDATA)>


<!-- END catalogue structure -->

<!-- mapset structure (OS) -->
<!ELEMENT mapset (eastingmin, eastingmax, northingmin, northingmax, eastingratio, northingratio, seriestitle, seriessub, county, mapsheet+, poi*)>
<!ELEMENT eastingmin (#PCDATA)>
<!ELEMENT eastingmax (#PCDATA)>
<!ELEMENT northingmin (#PCDATA)>
<!ELEMENT northingmax (#PCDATA)>
<!ELEMENT eastingratio (#PCDATA)>
<!ELEMENT northingratio (#PCDATA)>
<!ELEMENT seriestitle (#PCDATA)>
<!ELEMENT seriessub (#PCDATA)>
<!ELEMENT county (#PCDATA)>
<!ELEMENT mapsheet (tile, file, pubyear, swe, swn, nwe, nwn, nee, nen, see, sen)>
<!ATTLIST mapsheet id CDATA #REQUIRED>
<!ELEMENT tile (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT pubyear (#PCDATA)>
<!ELEMENT swe (#PCDATA)>
<!ELEMENT swn (#PCDATA)>
<!ELEMENT nwe (#PCDATA)>
<!ELEMENT nwn (#PCDATA)>
<!ELEMENT nee (#PCDATA)>
<!ELEMENT nen (#PCDATA)>
<!ELEMENT see (#PCDATA)>
<!ELEMENT sen (#PCDATA)>
<!ELEMENT poi (#PCDATA)>
<!ATTLIST poi easting CDATA #REQUIRED>
<!ATTLIST poi northing CDATA #REQUIRED>



<!-- entities -->
<!ENTITY % ent-isoamsa SYSTEM "isoamsa.ent">
%ent-isoamsa;
<!ENTITY % ent-isoamsb SYSTEM "isoamsb.ent">
%ent-isoamsb;
<!ENTITY % ent-isoamsc SYSTEM "isoamsc.ent">
%ent-isoamsc;
<!ENTITY % ent-isoamsn SYSTEM "isoamsn.ent">
%ent-isoamsn;
<!ENTITY % ent-isoamso SYSTEM "isoamso.ent">
%ent-isoamso;
<!ENTITY % ent-isoamsr SYSTEM "isoamsr.ent">
%ent-isoamsr;
<!ENTITY % ent-isobox SYSTEM "isobox.ent">
%ent-isobox;
<!ENTITY % ent-isocyr1 SYSTEM "isocyr1.ent">
%ent-isocyr1;
<!ENTITY % ent-isocyr2 SYSTEM "isocyr2.ent">
%ent-isocyr2;
<!ENTITY % ent-isodia SYSTEM "isodia.ent">
%ent-isodia;
<!ENTITY % ent-isogrk1 SYSTEM "isogrk1.ent">
%ent-isogrk1;
<!ENTITY % ent-isogrk2 SYSTEM "isogrk2.ent">
%ent-isogrk2;
<!ENTITY % ent-isogrk3 SYSTEM "isogrk3.ent">
%ent-isogrk3;
<!ENTITY % ent-isogrk4 SYSTEM "isogrk4.ent">
%ent-isogrk4;
<!ENTITY % ent-isolat1 SYSTEM "isolat1.ent">
%ent-isolat1;
<!ENTITY % ent-isolat2 SYSTEM "isolat2.ent">
%ent-isolat2;
<!ENTITY % ent-isonum SYSTEM "isonum.ent">
%ent-isonum;
<!ENTITY % ent-isopub SYSTEM "isopub.ent">
%ent-isopub;
<!ENTITY % ent-isotech SYSTEM "isotech.ent">
%ent-isotech;

<!ENTITY % ent-bhoa SYSTEM "bhoa.ent">
%ent-bhoa;

=== legislation/legislation-bho-to-clml/data/47452.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="47452" pubid="351" publish="true">
	<title>Charles II, 1672</title>
	<subtitle>Chapter III. An Act for enableing his Majestie to make Leases of his Lands belonging to the Dutchy of Cornwall. [Rot. Parl. 25 <emph type="i">C. II. nu.</emph>. 3.]</subtitle>
	<section id="s1">
		<head>Reasons for passing this A&bholigct;.</head>
		<para id="p1">
			<emph type="i">What Leases may be made of Lands belonging to the Duchy of Cornwall, and how.; Exception of entire Honors, Lordships, or Manors.</emph>
		</para>
		<para id="p2">Whereas many of the Lands belonging to the Dutchy of Cornwall have beene granted by Lease to the
Tennants, some for the Terme of one, two or three Lives, and some for diverse yeares determinable
upon one, two or three Lives, and others, for one and thirty yeares and under, which Leases are desired to be
renewed by many of the said Tennants. And whereas of late yeares diverse increased Rents have beene by Order
of the late Lord Treasurer reserved upon the said leased Lands of the said Dutchy for the Improvement of that
Revenue whereof the Tennants have complained to the Kings Majestie, who is gratiously pleased that they may
compound with his Officers for the discharge of those increased Rents, and be restored to the old Rents formerly
paid for their respe&bholigct;ive Tenements. and Lands. Now, to the end the same may be accordingly effe&bholigct;ed, and that
the said Tenants may be incouraged to renew their Leases and Estates, and thereby the better enabled to repaire
their Houses and provide for their Families, and to improve their Lands holden of the said Dutchy Bee it ena&bholigct;ed
by, the Kings most excellent Majestie, by and with the advice and consent of the Lords Spirituall and Temporall
and Commons in this present Parlyament assembled and by authoritie of the same That all Leases and Grants
made and to be made within three yeares next ensueing the end of this present Session of Parlyament by our
said Soveraigne Lord the King by Letters Patents or by Indenture under the Great Seale of England or under
the Seale of the Court of Exchequer of any Offices in the disposition of the Owner of the said Dutchy as Duke
of Cornwall, or of any Parks, Lands Tenements or Hereditaments now in Lease, or out of Lease, and not granted
by Copy of Court-Roll, other then entire Honours Lordshipps or Mannours parcell of the possessions of, or
annexed or belonging unto the said Dutchy of Cornwall shall be good and effe&bholigct;uall in Law according to the
purport and contents of the same Leases and Grants against our said Soveraigne Lord the King his Heires and
Successors and against all and every other person and persons that shall at any time hereafter have, inherite or
enjoy the said Dutchy by force of any A&bholigct; of Parlyament or by any other Limitation whatsoever.</para>
		<section id="s2">
			<head>II. For what Terms or Times.</head>
			<para id="p3">
				<emph type="i">Not dispunishable of Waste.; Ancient Rent, &amp;c. to be reserved.; Where no Rent was payable, then a reasonable Rent.</emph>
			</para>
			<para id="p4">Provided alwayes That every such Lease or Grant soe made or to be made be not made for more then one,
two or three Lives in Possession, or for thirty one yeares or under, or for some terme of yeares determinable
upon one two or three Lives and not above. And if such Leases and Grants be made in Reversion or Expe&bholigct;ancy
That then the same together with the Estates in Possession doe not exceede three Lives or the terme of thirty
and one yeares, and not in any wise dispunishable of Waste, and soe as upon every such Lease shall be reserved
the auntient or most usuall Rent or more, or such Rent as hath beene reserved, yeilded or paid for the same
Lands for the greater part of twenty yeares next before the makeing of the said Leases, and shall be reserved
due and payable to him or them that shall have the Inheritance or other Estate of the said Dutchy, And where
noe such Rent hath beene reserved or payable That then upon every such Lease there shall be reserved a reasonable
Rent not being under the twentieth part of the cleare yearely value of the Parks, Lands Tenements or
Hereditaments contained in such Lease, and all Leases and Grants otherwise made or to be made shall be null
and void.</para>
		</section>
		<section id="s3">
			<head>III. Covenants in the Leases to bind Reversioners, &amp;c.</head>
			<para id="p5">
				<emph type="i">General Saving, except the Right of the King and the Duke of Cornwall.</emph>
			</para>
			<para id="p6">And bee it further ordained and ena&bholigct;ed by the authoritie aforesaid That all Covenants Conditions Reservations
and other Agreements contained in every Lease or Grant made or to be made as aforesaid shall be good and
effe&bholigct;uall in Law according to the words and contents of the same aswell for and against them to whome the
Reversion of the same Lands Tenements or Hereditaments shall come, as for and against them to whome the
Interest of the said Leases or Grants shall come respe&bholigct;ively as if our Soveraigne Lord the Kings Majestie at the
time of the makeing of such Covenants Conditions and Reservations and other Agreements were seised of an
absolute Estate in Fee simple in the same Lands Tenements or Hereditaments. Saveing alwayes to all and every
person and persons Bodyes Pollitique and Corporate their H&eacute;ires and Successors Executors Administrators and
Assignes other then to our said Soveraigne Lord the King and his Heires, and the Duke and Dukes of Cornwall
for the time being and his and their Heires, and all and every person and persons that shall hereafter have,
inherite or enjoy the said Dukedome of Cornwall by force of any A&bholigct; of Parlyament or other Limitation whatsoever
all such [Rites,<ref idref="n1">1</ref>] Titles, Estates, Customes Interests Tenures Claimes and Demands whatsoever of what nature,
kinde or quality soever, of, in, to or out of the said Offices, Lands Tenements or Hereditaments or any of them
as they or any of them had or ought to have had before the makeing of this A&bholigct; to all intents and purposes,
and in as large and ample manner and forme as if this A&bholigct; had never beene had or made. This A&bholigct; or any
thing therein contained to the contrary notwithstanding.</para>
			<note id="n1" number="1">Rights <emph type="i">O</emph>.</note>
		</section>
	</section>
</report>

=== legislation/legislation-bho-to-clml/data/pubid-352/46400.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="46400" pubid="352" publish="true">
	<title>William and Mary, 1693</title>
	<subtitle>Chapter VI. An Act to prevent Disputes and Controversies concerning Royal Mines. [Rot. Parl. pt. 2. nu. 5.]</subtitle>
	<section id="s1">
		<head>Recital of 1 W. &amp; M. Sess. 1. c. 30.</head>
		<para id="p1">
			<emph type="i">Owners of Mines shall enjoy them</emph>.</para>
		<para id="p2">Whereas by a Clause in one Act of Parliament made in the First yeare of their Majesties Reigne entituled
An Act to repeal the Statute made in the Fifth yeare of King Henry the Fourth against the multiplying of
Gold and Silver It is amongst other things enacted that noe Mine of Tin Copper Iron or Lead shall hereafter be
adjudged reputed or taken to bee a Royal Mine although Gold or Silver may be extracted out of the same But
notwithstanding the good provision by the said Statute to prevent the discourageing their Majesties good Subjects
who have Mines of Copper Tin Iron or Lead in their Soyls from digging and opening the same many doubts
and questions have arisen upon the said Statute whereby great suits and troubles have arisen to many owners and
Proprietors of such Mines. Wherefore for the better explanac[i]on of the said Statute Be it enacted and declared by
the King and Queens most Excellent Majesties by and with the advice and consent of the Lords Spiritual and
Temporal and the Co[m]mons in this present Parliament assembled and by the Authority of the same That all and
every Person or Persons being Subjects of the Crowne of England Bodies Politick or Corporate that now are or
hereafter shall be the Owner or Owners Proprietor or Proprietors of any Mine or Mines within the Kingdom of
England Dominion of Wales or Towne of Berwick upon Tweed wherein any Ore now is or hereafter
shall be discovered opened found or wrought and in which there is Copper Tin Iron or Lead shall
and may hold and enjoy the same Mine or Mines and Ore and continue in the possession thereof
and dig and work the said Mine or Mines or Ore notwithstanding that such Mine or Mines or Ore
shall be pretended or claimed to be a Royall Mine or Royall Mines any Law Usage or Custom to the contrary
notwithstanding.</para>
		<section id="s2">
			<head>II. King shall have the Ore at a Rate.</head>
			<para id="p3">
				<emph type="i">Several Rates</emph>.</para>
			<para id="p4">Provided always and be it enacted and declared That their Majesties [ther<ref idref="n2">2</ref>] Heirs and Successors and all claimeing
any Royal Mines under them shall and may have the Ore of any such Mine or Mines in any part of the said
Kingdom of England Dominion of Wales or Towne of Berwick upon Tweed (other then Tin Ore in the Counties
of Devon and Cornwall) paying to the Proprietors or Owners of the said Mine or Mines wherein such Ore is
or shall be found within Thirty days after the said Ore is or shall bee raised and laid upon the Banks of the
said Mine or Mines and before the same be removed from thence the rates following (that is to say) For all
Ore washt made cleane and merchantable wherein is Copper the rate of Sixteen Pounds per Tun and for all Ore
washt made cleane and merchantable wherein there is Tin the rate of Fourty Shillings per Tun and for all Ore
washt made clean and merchantable wherein there is Iron the rate of Fourty Shillings per Tun and for all Ore
washt made cleane and merchantable wherein there is Lead the rate of Nine Pounds per Tun and in default of
payment of such respective sums as aforesaid it shall and may be lawfull for the Owners and Proprietors of the
said Mine or Mines wherein such Ore is are or shall be found to sell and dispose of the said Ore to his and
theire own uses any Law Statute or Custome to the contrary notwithstanding.</para>
		</section>
		<section id="s3">
			<head>III. Proviso for Charters, &amp;c. to Tinners of Devon and Cornwall.</head>
			<para id="p5">Provided always That nothing [conteined<ref idref="n2">2</ref>] in this Act shall alter determine or make void the Charters granted
to the Tinners of Devon and Cornwall by any of the Kings and Queens of this Realme or any of the Liberties
Priveledges or Franchises of the said Tinners or to alter determine or make void the Laws Customs or Constitutions
of the Stanneries of Devon or Cornwall or any of them.</para>
			<note id="n1" number="1">their <emph type="i">O</emph>.</note>
			<note id="n2" number="2">interlined on the Roll.</note>
		</section>
	</section>
</report>

=== legislation/legislation-bho-to-clml/data/pubid-351/47417.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="47417" pubid="351" publish="true">
	<title>Charles II, 1670</title>
	<subtitle>Chapter IX. An Act authorizing certaine Commissioners of the Realme of England to treate with Commissioners of Scotland
for the Weale of both Kingdomes. [Rot. Parl. 22. C. II. nu. 9.]</subtitle>
	<section id="s1">
		<head>Reasons for passing this A&bholigct;.</head>
		<para id="p1">
			<emph type="i">His Majesty may name Commissioners to treat with Commissioners of Scotland concerning a Union between both Realms.; Their Proceedings to be reduced into Writings tripartite, one for the King, one for the Parliament of England, and the Third for the Parliament of Scotland; and thereupon further Proceedings had as King and Parliament may think fit.</emph>
		</para>
		<para id="p2">Whereas the Kings most Excellent Majestie out of his Princely Zeale and Fatherly Care for the Welfare
and Happinesse of his Subje&bholigct;s persisting in the same pious and prudent Resolution of his Royall Grandfather
King James of ever blessed memory to endeavour a nearer and more compleate Union between his two Kingdomes
of England and Scotland, hath recommended it to the Parlyaments of both Kingdomes that Co&bhooov;missioners might be
nominated to treate and consult concerning this Union To the end that his Majestyes Royall and Gracious Purposes
therein may be accomplished, and such a further Union may be treated and agreed upon as may compleate and
confirme for ever a constant mutuall Love and Friendshipp betweene the Subje&bholigct;s of both Realmes Bee it ena&bholigct;ed
by the Kings most excellent Majestie by and with the advice and consent of the Lords Spirituall and Temporall
and of the Commons in this present Parlyament assembled and by the authoritie of the same That such persons
to be nominated by his Majestie under his Great Seale of England, Or such and soe many of them as shall in
that behalfe be appointed by his Majestie to be of the Quorum shall by force of this A&bholigct; have full Power Commission
and Authority at such time and times and in such place or places as his Majestie shall please to appoint to assemble
and meete, and thereupon to treate and consult according to the Tenoure or Purporte of their Authority or
Commission in that behalfe, with certaine Commissioners to be authorized by Authority of the Parlyament of Scotland
of and concerning such an Union of the said Realmes of England and Scotland and of and concerning such other
matters causes and things whatsoever as upon mature deliberation and consideration the greatest part of the said
Commissioners assembled as aforesaid, and the Commissioners authorized or to be authorized by the Parlyament of
Scotland according to the Tenoure or Purporte of their Commission in that behalfe shall in their Wisedomes thinke
convenient and necessary for the Honour of his Majestie and the weale and common Good of both the said
Kingdomes dureing his Majestyes Life (which Almighty God long preserve) and of his Heires and lawfull Successors
for ever, Which Commissioners of both the said Realmes shall according to the Tenor or Purporte of their said
Authorityes or Commissions in that behalfe, reduce their doeings and proceedings therein into Writeings, or
Instruments Tripartite every part to be subscribed and sealed by them, to the end that one part thereof may in
all humblenesse be presented to his most Excellent Majestie; Another part thereof to be offered to the consideration
of the Parlyament for the Realme of England, and another to be offered to the consideration of the Parlyament
for the Realme of Scotland at their next Sessions which shall be held in each Kingdome respe&bholigct;ively after such
Writeings or Instruments shall be subscribed and sealed by the said Commissioners; that thereupon such further
Proceedings may be had as by His Majestie and both the said Parlyaments shall be thought fitt and necessary for
the weale and common Good of both the said Kingdomes, to whom the intire Consideration of the whole and
the allowing or disallowing thereof, or any part thereof as they shall thinke fitt is wholly reserved.</para>
		<section id="s2">
			<head>II. Nothing of force till confirmed by Parliament of England.</head>
			<para id="p3">[Provided alsoe, and bee it ena&bholigct;ed and declared That noe matter or thing to be treated of, agreed or proposed
by the said Commissioners by vertue of this A&bholigct; shall have any force or effe&bholigct; or be put in Execution untill it
be confirmed and established by A&bholigct; of the Parlyament of England.<ref idref="n1">1</ref>]</para>
			<note id="n1" number="1">annexed to the Original A&bholigct; in a separate Schedule.</note>
		</section>
	</section>
</report>
