=== legislation/legislation-bho-to-clml/data/dtd/bho/report.dtd
<!ELEMENT report (title, subtitle, (page*,section*,geodata?))>
<!ATTLIST report 
         id CDATA #REQUIRED
         pubid CDATA #REQUIRED
         publish CDATA #IMPLIED>
<!--         publish (false|true) "true"> -->
<!-- added for LIWW -->
<!--! Jonathan altered some some elements' scope to account for London Inhabitants Without the Walls: name;  -->

<!ELEMENT subtitle (#PCDATA|emph|ref)*>

<!-- narrative content -->
<!ELEMENT section (head,(para|list|table|note|figure|plate|quote|section|fig|name|business|dataset|catalogue|mapset|page)*)>
<!ATTLIST section 
         id CDATA #REQUIRED
         title CDATA #IMPLIED
         type CDATA #IMPLIED>
<!ELEMENT head (#PCDATA|ref|emph|plt)*>
<!ELEMENT para (#PCDATA|ref|emph|person|glink|plt|br|page|mdr)*>
<!ATTLIST para id CDATA #REQUIRED>
<!ELEMENT person (#PCDATA)>
<!ELEMENT glink (#PCDATA)>
<!ELEMENT quote (quotext|quosource)*>
<!ATTLIST quote id ID #REQUIRED>
<!ELEMENT quotext (quoline)*>
<!ELEMENT quoline (#PCDATA|ref|emph|page)*>
<!ELEMENT quosource (#PCDATA|ref|emph)*>
<!ELEMENT emph (#PCDATA|emph|ref|page|br|mdr)*>
<!ATTLIST emph type (b|i|p|d|c|k|u) #REQUIRED>
<!ELEMENT fig (#PCDATA)>
<!ATTLIST fig idref IDREF #IMPLIED>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!-- English Heritage only-->
<!ELEMENT plt (#PCDATA)>
<!ATTLIST plt target CDATA #REQUIRED>

<!-- in text markers to footnotes-->
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref idref IDREF #IMPLIED>
<!ATTLIST ref type (footnote|reference|addenda) "footnote">

<!-- in text graphics -->
<!ELEMENT figure (title|caption)*>
<!ATTLIST figure 
         id ID #REQUIRED
         number CDATA #REQUIRED
         graphic CDATA #REQUIRED
         visible CDATA #IMPLIED>
<!-- English Heritage only-->
<!ELEMENT plate (title|caption)*>
<!ATTLIST plate 
         id ID #REQUIRED
         number CDATA #REQUIRED
         graphic CDATA #REQUIRED>

<!ELEMENT title (#PCDATA|emph|ref)*>
<!ELEMENT caption (#PCDATA|ref|emph|br)*>

<!-- footnotes, referenced using ref tag-->
<!ELEMENT note (#PCDATA|ref|emph|br|plt|figure|table|para|page)*>
<!ATTLIST note 
         id ID #REQUIRED
         number CDATA #REQUIRED
         type (footnote|reference|addenda) "footnote">

<!-- Table, dervied from html-->
<!ELEMENT table (head?,(tr|page)+)>
<!ATTLIST table 
         id CDATA #REQUIRED
         caption CDATA #IMPLIED
         number CDATA #IMPLIED>
<!ELEMENT tr (th|td)*>
<!ATTLIST tr 
         id ID #IMPLIED>



<!ELEMENT th (#PCDATA|ref|emph|br|plt)*>
<!ELEMENT td (#PCDATA|ref|emph|br|plt|page|mdr|list)*>

<!ATTLIST th
         cols CDATA #IMPLIED
         rows CDATA #IMPLIED>
<!ATTLIST td
         cols CDATA #IMPLIED
         rows CDATA #IMPLIED>
<!ELEMENT place (#PCDATA)*>
<!ATTLIST place id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA|nhead|nsub|page|ref)*>
<!ELEMENT nhead (#PCDATA|place|nkey|ref)*>
<!ELEMENT nkey (#PCDATA|ref)*>
<!ELEMENT nsub (#PCDATA|place|ref)*>

<!-- list, derived from html-->
<!ELEMENT list (head,(li|page)+)>
<!ELEMENT li (#PCDATA|page|ref|emph|br)*>
<!ATTLIST list id CDATA #REQUIRED>

<!-- in-text line break-->
<!ELEMENT br EMPTY>

<!-- new page tokens -->
<!ELEMENT page EMPTY>
<!ATTLIST page start CDATA #REQUIRED>
<!ATTLIST page pubid CDATA #IMPLIED>

<!-- CSP modern document references -->
<!ELEMENT mdr (#PCDATA)>
<!ATTLIST mdr id CDATA #REQUIRED>

<!-- depracted business directory -->
<!ELEMENT business (house,street,ward,occupier,trade, (staff*))>
<!ELEMENT house (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT ward (#PCDATA)>
<!ELEMENT occupier (#PCDATA)>
<!ELEMENT trade (#PCDATA)>
<!ELEMENT staff (#PCDATA)>

<!-- 1st generation dataset structure -->
<!ELEMENT geodata (geoclass+,geolocation+,geoitem+)>

<!ELEMENT geoclass (label,description,shortdesc,scale)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT description (#PCDATA|emph)*>
<!ELEMENT shortdesc (#PCDATA)>
<!ELEMENT scale (range)+>
<!ELEMENT range (#PCDATA)>

<!ATTLIST geoclass id ID #REQUIRED>
<!ATTLIST geoclass type (year|sterling) "year">
<!ATTLIST range id ID #REQUIRED>
<!ATTLIST range begin CDATA #REQUIRED>
<!ATTLIST range end CDATA #REQUIRED>

<!ELEMENT geolocation (#PCDATA)>
<!ATTLIST geolocation id ID #REQUIRED>
<!ATTLIST geolocation section CDATA #IMPLIED>
<!ATTLIST geolocation coordx CDATA #REQUIRED>
<!ATTLIST geolocation coordy CDATA #REQUIRED>

<!ELEMENT geoitem (#PCDATA)>
<!ATTLIST geoitem id ID #REQUIRED>
<!ATTLIST geoitem class IDREF #REQUIRED>
<!ATTLIST geoitem place IDREF #REQUIRED>



<!-- 2nd generation dataset structure -->
<!ELEMENT dataset (dsclass+,dsrecord+)>
<!ELEMENT dsclass (label,description,shortdesc?,scale?)>
<!ATTLIST dsclass id ID #REQUIRED>
<!ATTLIST dsclass type (year|sterling|text|integer|geox|geoy) "text">
<!ATTLIST dsclass sortkey CDATA #REQUIRED>
<!ATTLIST dsclass showheader (True|False) "True">
<!ATTLIST dsclass showcolumn (True|False) "True">
<!ATTLIST dsclass width CDATA #IMPLIED>
<!-- standard, that dsclass c0 in all cases should describe the main record -->
<!ELEMENT dsrecord (prop+)>
<!ATTLIST dsrecord id ID #REQUIRED>
<!ATTLIST dsrecord coordx CDATA #IMPLIED>
<!ATTLIST dsrecord coordy CDATA #IMPLIED>
<!ELEMENT prop (#PCDATA|ref|emph|br)*>
<!ATTLIST prop class IDREF #REQUIRED>



<!-- catalogue structure -->
<!ELEMENT catalogue (group+)>
<!ATTLIST catalogue classref CDATA #REQUIRED>
<!ELEMENT group (head,(item|group)*)>
<!ATTLIST group id ID #REQUIRED>
<!ELEMENT item (#PCDATA)>


<!-- END catalogue structure -->

<!-- mapset structure (OS) -->
<!ELEMENT mapset (eastingmin, eastingmax, northingmin, northingmax, eastingratio, northingratio, seriestitle, seriessub, county, mapsheet+, poi*)>
<!ELEMENT eastingmin (#PCDATA)>
<!ELEMENT eastingmax (#PCDATA)>
<!ELEMENT northingmin (#PCDATA)>
<!ELEMENT northingmax (#PCDATA)>
<!ELEMENT eastingratio (#PCDATA)>
<!ELEMENT northingratio (#PCDATA)>
<!ELEMENT seriestitle (#PCDATA)>
<!ELEMENT seriessub (#PCDATA)>
<!ELEMENT county (#PCDATA)>
<!ELEMENT mapsheet (tile, file, pubyear, swe, swn, nwe, nwn, nee, nen, see, sen)>
<!ATTLIST mapsheet id CDATA #REQUIRED>
<!ELEMENT tile (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT pubyear (#PCDATA)>
<!ELEMENT swe (#PCDATA)>
<!ELEMENT swn (#PCDATA)>
<!ELEMENT nwe (#PCDATA)>
<!ELEMENT nwn (#PCDATA)>
<!ELEMENT nee (#PCDATA)>
<!ELEMENT nen (#PCDATA)>
<!ELEMENT see (#PCDATA)>
<!ELEMENT sen (#PCDATA)>
<!ELEMENT poi (#PCDATA)>
<!ATTLIST poi easting CDATA #REQUIRED>
<!ATTLIST poi northing CDATA #REQUIRED>



<!-- entities -->
<!ENTITY % ent-isoamsa SYSTEM "isoamsa.ent">
%ent-isoamsa;
<!ENTITY % ent-isoamsb SYSTEM "isoamsb.ent">
%ent-isoamsb;
<!ENTITY % ent-isoamsc SYSTEM "isoamsc.ent">
%ent-isoamsc;
<!ENTITY % ent-isoamsn SYSTEM "isoamsn.ent">
%ent-isoamsn;
<!ENTITY % ent-isoamso SYSTEM "isoamso.ent">
%ent-isoamso;
<!ENTITY % ent-isoamsr SYSTEM "isoamsr.ent">
%ent-isoamsr;
<!ENTITY % ent-isobox SYSTEM "isobox.ent">
%ent-isobox;
<!ENTITY % ent-isocyr1 SYSTEM "isocyr1.ent">
%ent-isocyr1;
<!ENTITY % ent-isocyr2 SYSTEM "isocyr2.ent">
%ent-isocyr2;
<!ENTITY % ent-isodia SYSTEM "isodia.ent">
%ent-isodia;
<!ENTITY % ent-isogrk1 SYSTEM "isogrk1.ent">
%ent-isogrk1;
<!ENTITY % ent-isogrk2 SYSTEM "isogrk2.ent">
%ent-isogrk2;
<!ENTITY % ent-isogrk3 SYSTEM "isogrk3.ent">
%ent-isogrk3;
<!ENTITY % ent-isogrk4 SYSTEM "isogrk4.ent">
%ent-isogrk4;
<!ENTITY % ent-isolat1 SYSTEM "isolat1.ent">
%ent-isolat1;
<!ENTITY % ent-isolat2 SYSTEM "isolat2.ent">
%ent-isolat2;
<!ENTITY % ent-isonum SYSTEM "isonum.ent">
%ent-isonum;
<!ENTITY % ent-isopub SYSTEM "isopub.ent">
%ent-isopub;
<!ENTITY % ent-isotech SYSTEM "isotech.ent">
%ent-isotech;

<!ENTITY % ent-bhoa SYSTEM "bhoa.ent">
%ent-bhoa;

=== legislation/legislation-bho-to-clml/data/pubid-351/47198.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="47198" pubid="351" publish="true">
	<title>Charles I, 1625</title>
	<subtitle>Chapter II. An Acte to enable the King to make Leases of Land&bholngs; parcell of his Highnes Duchie of Cornewall, or annexed
to the same.[Rot. Parl. nu. 2.]</subtitle>
	<section id="s1">
		<head>Contra&bholigct;s for Leases made by the King, as Duke of Cornwall, under St. 21 Jac. I. c. 29. interrupted by his Accession to the Crown;</head>
		<para id="p1">
			<emph type="i">Leases of Lands of the Duchy to be made by the King within Three Years, declared valid.</emph>.</para>
		<para id="p2">WHEREAS the King our Soveraigne Lord, being in the life tyme of his Royall Father of blessed memorie, seised
of the said Dukedome of Cornewall, did bargayne and contra&bholigct; for Leases and Estates to be made of divers
Mesuages Land&bholngs; Tenement&bholngs; and Hereditament&bholngs; parcell of the said Dukedome of Cornewall, which Leases and Estates,
his Majestie was enabled to have made in his said Fathers life tyme, by an A&bholigct; of Parliament made in the last Session
of Parliament, intituled, An A&bholigct;e to enable the most excellent Prince Charles to make Leases of Land&bholngs;, parcell of His
Highnes Dutchy of Cornewall, or annexed to the same. And because His Majestie, having received divers Fines, and
s&bhooov;mes of Mony, according to the said Contra&bholigct;&bholngs;, and having entred into Treatie with divers others for like Estates; the
finishing of which-Contra&bholigct;&bholngs; and making the said Leases, was &bhopcrl;vented by His Majesties accesse to the Imperiall Crowne
of this Realme, is graciouslie pleased for the good of his poore Tenant&bholngs; of the said Duchie Land&bholngs;, to proceed to the
full accomplishment of the Contra&bholigct;&bholngs;, and Leases of the &bhopcrl;misses: Be it therefore ena&bholigct;ed by our said Soveraigne Lord
the Kinge, the Lord&bholngs; Spirituall and Temporall, and C&bhooov;mons in this &bhopcrl;sent Parliament assembled; and by authoritie of
this &bhopcrl;sent Parliament, That all Leases to be made within the space of three yeares now next ensuing by our said
Soveraigne Lord the King, by Letters Patent&bholngs;, Indentures, or other writing&bholngs; under his great Seale of England, or Seale
of the Court of Exchequer of any Mannors Land&bholngs; Tenement&bholngs; or Hereditament&bholngs; parcell of the possessions of the said
Dutchy of Cornewall or annexed to the same shalbe good and effe&bholigct;uall in Lawe according to the purport and
content of the said Leases against our Soveraigne Lord the King&bholngs; Majestie his heires and successors and against all
and every &bhopubr;son or &bhopubr;sons that shall hereafter have inherite or enjoye the said Dukedome of Cornewall by force of any
A&bholigct; of Parliament or other limitacion whatsoever.</para>
		<section id="s2">
			<head>II. Such Leases shall not exceed the Term of Three Lives or Thirty-one Years, under ancient or reasonable Rent.</head>
			<para id="p3">Provided alwaies, That every such Lease so to be made of any Mannors Land&bholngs; Tenement&bholngs; or Hereditament&bholngs; in
possession, shalbe made but for three lives or fewer or for one and thirtie yeares or under, or some other terme of yeares
determinable uppon one two or three lives, and not above. And if such Leases be made in revercion, that then the
same together with the Estates in possession do not exceed three lives or the terme of one and thirtie yeares, and not
in any wise dispunishable of wast: and so as uppon every such Lease shalbe reserved the auncient or most usuall Rent,
or such Rent as hath beene yeilded or paid for the greater part of twentie yeares next before the making of the said
Leases, and shalbe reserved due and payable, by, or to him or her that shall have the inheritance or other Estate of
the said Mannors Land&bholngs; Tenement&bholngs; or Hereditament&bholngs;. And where no such Rent hath bene reserved or payable, that
then uppon every such Lease; there shalbe reserved a reasonable Rent, not being under the twentith part of the
cleere yearelie value of the Mannors, Landes, Tenement&bholngs;, or Hereditament&bholngs;, contayned in such Lease.</para>
		</section>
		<section id="s3">
			<head>III. Covenants in such Leases good for and against Reversioners, &amp;c.</head>
			<para id="p4">And be it further ordained and ena&bholigct;ed by authoritie of this &bhopcrl;sent parliament, That all Covenaunt&bholngs;, Condicions, and
Reservacions and other agreement&bholngs; conteyned in every Lease so to be made as aforesaid, shalbe good and effe&bholigct;uall in
Lawe, according to the word&bholngs; and content&bholngs; of the same, aswell for and against them, to whome the Reversion of the
same Mannors, Landes, Tenement&bholngs; or Hereditament&bholngs; shall come, as for and against them to whome the said Leases shall
come, respe&bholigct;ivelie: as if our said Soveraigne Lord the King&bholngs; Majestie at the tyme of the making of such Coven<emph type="p">a</emph>nt&bholngs;,
Condicions, and Reservacions, and other Agreement&bholngs; were seised of an absolute and indefesible estate in Fee simple,
in the same Mannors, Land&bholngs;, Tenement&bholngs; or Hereditaments.</para>
		</section>
		<section id="s4">
			<head>IV. General Saving.</head>
			<para id="p5">Saving alwaies to all and every &bhopubr;son and &bhopubr;sons bodies Politique and Corporate, their Heires and Successors,
Executors, Administrators, and Assignes, (other then our said Soveraigne Lord the King&bholngs; Majestie and his Heires,
and all and every &bhopubr;son and &bhopubr;sons, that shall heareafter have, inherite or enjoye the said Dukedome of Cornewall, by
force of any A&bholigct;e of Parliament, or other limitacion whatsoever) all such right&bholngs;, titles, estates, customes, interest&bholngs;, termes,
claimes, and demaund&bholngs; whatsoever, of what kinde, nature, or qualitie whatsoever, of, in, to, or out of the said Mannors,
Landes, Tenement&bholngs;, or Hereditament&bholngs;, or any of them, as they or any of them had, or ought to have had before the
making of this A&bholigct;, to all intent&bholngs; and purposes, and in as large and ample manner and forme, as if this Acte had
never byn had or made. This Acte or any thing therein conteyned to the contrary notwithstanding.</para>
		</section>
	</section>
</report>

=== legislation/legislation-bho-to-clml/data/pubid-351/47298.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="47298" pubid="351" publish="true">
	<title>Charles II, 1661</title>
	<subtitle>An Act for Confirming an Act Entituled An Act for encouraging and encreasing of Shipping &amp; Navigation and severall other Acts both publique and private mentioned therein.</subtitle>
	<section id="s1">
		<head>Recital that during the Troubles the Lords and Commons were assembled, and several &bholigct;s were passed of necessary Use.</head>
		<para id="p1">
			<emph type="i">12 Car. II. c. 18.; c.32.; c.36.; c.34.; c.13.; c.6.; 12 Car. II. pr. ante p. 253.; confirmed and declared to have the full force of &bholigct;s of Parliament</emph>.</para>
		<para id="p2">WHEREAS during the late difficulties &amp; exigencies of affaires in the absence of His most Excellent
Majestie and in reference to His return from beyond the Seas into those His Majesties Dominions The
Lords and Commons being assembled att Westminster the five and twentieth day of Aprill in the twelfth yeare
of His Majesties Reigne were from thence and after his Majesties returne continued untill the nine and twentieth
day of December then next following and now last past and then dissolved by his Majestie In which time severall
&bholigct;s were passed by his Majesty by and with the advice &amp; consent of the [said<ref idref="n1">1</ref>] Lords and Commons assembled
as aforesaid which being of necessary use are fitt to be continued and confirmed although the manner of the said
assembling enforced by the difficulties and exigencies aforesaid which then lay upon the Nation is not to bee
into example Bee it therefore En&bholigct;ed by the Kings most Excellent Majesty by and with the advice and
consent of the Lords and Commons in this present Parliament assembled and by the Authority of the same That
all and singuler the &bholigct;s made or men&bhocotil;ned to be made by his said Majesty by and with the advice or [consents<ref idref="n2">2</ref>]
of the Lords and Commons upon or since the said five and twentieth day of Aprill herein after particularly
men&bhocotil;ned and expressed (that is to say) One &bholigct; Entituled An &bholigct; for the encouraging and encreasing of
Shipping and Navigation One other &bholigct; Entituled An &bholigct; for Prohibiting the Exportation of Wool Wool Fells
Fullers Earth or any kind of Scouring Earth One other &bholigct; Entituled An &bholigct; impowring the Master of the Rolls
for the time being to make Leases for yeares in order to new build the old Houses belonging to the Rolls One
other &bholigct; Entituled An &bholigct; for prohibiting the planting setting or sowing of Tobacco in England and Ireland One
other &bholigct; Entituled An &bholigct; for restraining the takeing of excessive Usury One other &bholigct; Entituled An &bholigct; for
the present nominating of Commissioners of Sewers One other &bholigct; Entituled An &bholigct; for the Incorporating of the
Master and Wardens of the Company of Haberdashers London to be Governors of the Free Schoole &amp; Almes
houses in Newport in the County of Salop of the Foundation of William Adams and for setling of Lands and
Possessions on them for maintenance thereof and other charitable uses. And all and every the Clauses Sentences
and Articles in them and every of them contained shall be and [are hereby ratified<ref idref="n3">3</ref>] and confirmed and en&bholigct;ed
and declared to have the full force and strength of &bholigct;s of Parliament according to the tenor and purport thereof
and soe shall be adjudged deemed and taken to all intents and purposes whatsoever and as if the same had beene
made declared and en&bholigct;ed by Authority of this present Parliament.</para>
		<note id="n1" number="1">interlined on the Roll.</note>
		<note id="n2" number="2">Consent <emph type="i">O</emph>.</note>
		<note id="n3" number="3">hereby are <emph type="i">O</emph>.</note>
	</section>
</report>

=== legislation/legislation-bho-to-clml/data/pubid-352/46398.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="46398" pubid="352" publish="true">
	<title>William and Mary, 1693</title>
	<subtitle>An Act to repeal a Clause in the Statute made in the [34th and 35th] years of King Henry the Eighth by which Justices of Peace in Wales are limitted to Eight in each County. [Chapter IV. Rot. Parl. pt. 2. nu. 3.]</subtitle>
	<section id="s1">
		<head></head>
		<para id="p1">
			<emph type="i">Recital that 34 &amp; 35 H. VIII. c. 26. &sect; 55. has been found to be inconvenient.; By Commission under the Great Seal,; the King may nominate any Number of Justices in Wales</emph>.</para>
		<para id="p2">Whereas in a Statute made in the thirty fourth and thirty fifth yeares of the Reigne of King Henry the
Eighth entituled An Act for certaine Ordinances in the Kings Majesties Dominions and principality of
Wales there is a Clause or Article contained in these words that is to say Item that there shall not exceed the
number of Eight Justices of the Peace in any of the said Shires over and besides the President Council and Justices
aforesaid and the Kings Attorney and Sollicitor Which President Council Justices and the Kings Attorney and
Sollicitor shall be put in every Co[m]mission of Peace in every of the said Twelve Shires. And whereas the Law
contained in this Clause or Article is by experience found to be inconvenient be it therefore enacted by the King
and Queens most excellent Majestie by and with the advice and consent of the Lords Spiritual and Temporal
and Commons in Parliament assembled and by authority of the same That the said Clause or Article be from
henceforth absolutely repealed and vacated to all intents and purposes And that it shall and may be lawfull to and
for the King and Queens most excellent Majesties their heires and Successors by Commission under the Greate
Seale of England to constitute nominate and appoint from time to time any such number of persons to bee Justices
of Peace in any of the said Counties of Wales as they shall thinke fitting and convenient according to such wayes
and methods as are co[m]monly used for the constituteing nominateing and appointing of Justices of the Peace in
and for any County of England And that the persons so constituted nominated and appointed shall have power
and authority to act and [to<ref idref="n1">1</ref>] doe any manner of thing pertaining to the Office of a Justice of Peace in as large
and ample manner as any Justice or Justices of the Peace within the Dominion of Wales might or ought to have
done before the makeing of this Act Any Law Statute Usage or Ordinance to the contrary in any wise
notwithstanding.</para>
		<note id="n1" number="1">interlined on the Roll.</note>
	</section>
</report>

=== legislation/legislation-bho-to-clml/data/pubid-352/46358.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="46358" pubid="352" publish="true">
	<title>William and Mary, 1691</title>
	<subtitle>Chapter IV. An Act for Preserving Two Ships Lading of Bay Salt taken as Prize for the Benefitt of Their Majesties Navy [Rot. Parl. pt. 1. nu. 4.]</subtitle>
		<section id="s1">
			<head>1 W. &#x0026; M. Sess. 1. c. 34. recited.</head>
			<para id="p1">
				<emph type="i">2 W. &#x0026; M. Sess. 2. c. 14. recited.; Recital that Two Ships laden with Bay Salt of France are in the Port of Dover.; The said Bay Salt on board the said Ships condemned, or if condemned as Prize, to be used for the Navy</emph>.</para>
			<para id="p2">WHEREAS by an Act made in the First Yeare of Their Majesties Reigne Entituled An Act for Prohibiting
all Trade and Commerce with France It was amongst other things Provided That from and after the
Four and twentieth Day of August therein mentioned no French Wines Vinegar Brandy Linen Silks Salt Paper
or any other Goods or Com[m]odities whatsoever of the Growth Product or Manufacture of any of the Dominions
or Territories of the French King should dureing the time in the said Act limitted be brought in by Land or
Imported in any Ship or Ships Vessel or Vessels whatsoever into any Port Haven Creek or other Place whatsoever
in the Kingdoms of England or Ireland the Dominion of Wales or Towne of Berwick upon Tweed or Isles of
Jersey Guernsey Alderney Sark or Isle of Man from any Place or Port whatsoever And that if any such Goods
or other Com[m]odities of the Growth p[re]duct or Manufacture of France or of the Territories or Dominions of the
French King should be imported contrary to the said Act they should be staved spilt destroyed or burnt in
such manner as is by the said Act directed And whereas by another Act made in the Second Yeare of Their
Majesties Reigne Entituled An Act for the more Effectuall putting in Execuc[i]on an Act [intituled An Act<ref idref="n1">1</ref>] for
Prohibiting all Trade [or<ref idref="n2">2</ref>] Com[m]erce with France thereby reciting the said former Act It is amongst other
things provided That if any Officer or Officers of the Customes or Prizes should wilfully or knowingly suffer
any of the said Goods Com[m]odities or Manufactures imported as Prizes or otherwise contrary to the said Act, to
be admitted to an Entry or to be imbezelled and not staved spilt burnt or destroyed in such manner as by
the said first Recited Act is directed Every such Officer or Officers should (being thereof lawfully convicted)
forfeit the Sum[m]e of Five hundred pounds and alsoe should for ever afterwards be incapable of having or executing
any Office in Their Majesties Revenue And whereas there are now in Their Majesties Harbour of Dover two
Vessels Laden with Bay Salt of the Product of France and brought in there as Prizes The one called the Unicorne
of the Burden of Three hundred Tuns or thereabouts &#x0026; taken by Captain William Young and Captain Henry
Martin or one of them The other called the Half Moon and taken by Captain Joseph Phines The first whereof
is already condemned as Prize Now forasmuch as the said Bay Salt will be of present Use for the preserving of
Victuals to be provided for Their Majesties Navy whereby it will be more for Their Majesties Service and the
Interest of the Kingdom That the said Bay Salt so brought in and imported in the said two Vessels before
menc[i]oned be preserved and applied to the Use and Purpose aforesaid then that the same should be burnt and
destroyed as is directed by the said Act Be it therefore Enacted by the King and Queens Most Excellent
Majesties by and with the Advice and Consent of the Lords Spiritual, and Temporal and Comons in Parliament
Assembled and by the Authority of the same That the said Bay Salt now being and remaining in the said Vessel
called the Unicorn and which is already condemned as Prize As also the said Bay Salt being and remaining
in the said Vessell called the Half Moon if the same shall be condemned as lawful Prize shall be applied and
disposed for the Use and Service of Their Majesties Navy And for that purpose shall be delivered unto the
Comissioners for the Victualling of Their Majesties Navy or to some or one of them or to such p[er]son or p[er]sons
as shall be Authorized by the said Comissioners or any three of them to receive the same to be Applied for
the Use and Service of Their Majesties Navy and to no other Use or Purpose whatsoever and shall not be
burnt or destroyed as in and by the said recited Acts is directed And that no Forfeiture Penalty or Disability
shall be incurred by any p[er]son or p[er]sons for or by reason thereof Any thing in the [said recited<ref idref="n1">1</ref>] Acts contained
or any other Act Statute or Law to the contrary notwithstanding</para>
		<section id="s2">
			<head>II. Commissioners for Victualling the Navy to pay for the said Salt.</head>
			<para id="p3">And be it further Enacted by the Authority aforesaid That upon Delivery of the said Bay Salt to the said
Comissioners for the Victualling of Their Majesties Navy as aforesaid It shall and may be lawfull to and for
the said Comissioners to pay for the same unto the said p[er]son or p[er]sons by whom the said Vessel or Vessels were
severally taken as aforesaid any Sume or Sumes of Money not exceeding the Rate and Price of One shilling and
Six pence [for each Bushell<ref idref="n3">3</ref>] or of Three pounds for every Wey of the said Salt and to Charge the same to
[Their Majesties Account which is thereupon to be allowed Any thing in the said Recited Acts or any other Act
Statute or Law to the contrary in any wise notwithstanding</para>
		</section>
		<section id="s3">
			<head>III. Disposing of the said Salt for any other Use;</head>
			<para id="p4">
				<emph type="i">Penalty 20s</emph>.</para>
			<para id="p5">Provided always and be it Enacted by the Authority aforesaid That if any p[er]son or p[er]sons shall dispose of
any of the Salt before mentioned for any other Use or Uses then for the Victualling of Their Majesties Navy
as is herein before menc[i]oned such p[er]son and p[er]sons shall forfeit for every Bushel of such Salt so disposed of
contrary to the Intent aforesaid the Sum of Twenty shillings to be Recovered by Acc[i]on of Debt Bill Plaint or
Informac[i]on in any of Their Majesties Courts of Record at Westminster wherein no Essoign p[re]tection or Wager of
Law nor any more then one Imparlance shall be allowed one Moyety of such Forfeiture shall be to Their Majesties
the other Moyety to him or them that will sue for the same</para>
			<note id="n1" number="1">interlined on the Roll.</note>
			<note id="n2" number="2">and, in the King's Printer's Copy.</note>
			<note id="n3" number="3">interlined on the Roll.</note>
		</section>
	</section>
</report>
