=== legislation/legislation-bho-to-clml/data/dtd/bho/report.dtd
<!ELEMENT report (title, subtitle, (page*,section*,geodata?))>
<!ATTLIST report 
         id CDATA #REQUIRED
         pubid CDATA #REQUIRED
         publish CDATA #IMPLIED>
<!--         publish (false|true) "true"> -->
<!-- added for LIWW -->
<!--! Jonathan altered some some elements' scope to account for London Inhabitants Without the Walls: name;  -->

<!ELEMENT subtitle (#PCDATA|emph|ref)*>

<!-- narrative content -->
<!ELEMENT section (head,(para|list|table|note|figure|plate|quote|section|fig|name|business|dataset|catalogue|mapset|page)*)>
<!ATTLIST section 
         id CDATA #REQUIRED
         title CDATA #IMPLIED
         type CDATA #IMPLIED>
<!ELEMENT head (#PCDATA|ref|emph|plt)*>
<!ELEMENT para (#PCDATA|ref|emph|person|glink|plt|br|page|mdr)*>
<!ATTLIST para id CDATA #REQUIRED>
<!ELEMENT person (#PCDATA)>
<!ELEMENT glink (#PCDATA)>
<!ELEMENT quote (quotext|quosource)*>
<!ATTLIST quote id ID #REQUIRED>
<!ELEMENT quotext (quoline)*>
<!ELEMENT quoline (#PCDATA|ref|emph|page)*>
<!ELEMENT quosource (#PCDATA|ref|emph)*>
<!ELEMENT emph (#PCDATA|emph|ref|page|br|mdr)*>
<!ATTLIST emph type (b|i|p|d|c|k|u) #REQUIRED>
<!ELEMENT fig (#PCDATA)>
<!ATTLIST fig idref IDREF #IMPLIED>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!-- English Heritage only-->
<!ELEMENT plt (#PCDATA)>
<!ATTLIST plt target CDATA #REQUIRED>

<!-- in text markers to footnotes-->
<!ELEMENT ref (#PCDATA)>
<!ATTLIST ref idref IDREF #IMPLIED>
<!ATTLIST ref type (footnote|reference|addenda) "footnote">

<!-- in text graphics -->
<!ELEMENT figure (title|caption)*>
<!ATTLIST figure 
         id ID #REQUIRED
         number CDATA #REQUIRED
         graphic CDATA #REQUIRED
         visible CDATA #IMPLIED>
<!-- English Heritage only-->
<!ELEMENT plate (title|caption)*>
<!ATTLIST plate 
         id ID #REQUIRED
         number CDATA #REQUIRED
         graphic CDATA #REQUIRED>

<!ELEMENT title (#PCDATA|emph|ref)*>
<!ELEMENT caption (#PCDATA|ref|emph|br)*>

<!-- footnotes, referenced using ref tag-->
<!ELEMENT note (#PCDATA|ref|emph|br|plt|figure|table|para|page)*>
<!ATTLIST note 
         id ID #REQUIRED
         number CDATA #REQUIRED
         type (footnote|reference|addenda) "footnote">

<!-- Table, dervied from html-->
<!ELEMENT table (head?,(tr|page)+)>
<!ATTLIST table 
         id CDATA #REQUIRED
         caption CDATA #IMPLIED
         number CDATA #IMPLIED>
<!ELEMENT tr (th|td)*>
<!ATTLIST tr 
         id ID #IMPLIED>



<!ELEMENT th (#PCDATA|ref|emph|br|plt)*>
<!ELEMENT td (#PCDATA|ref|emph|br|plt|page|mdr|list)*>

<!ATTLIST th
         cols CDATA #IMPLIED
         rows CDATA #IMPLIED>
<!ATTLIST td
         cols CDATA #IMPLIED
         rows CDATA #IMPLIED>
<!ELEMENT place (#PCDATA)*>
<!ATTLIST place id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA|nhead|nsub|page|ref)*>
<!ELEMENT nhead (#PCDATA|place|nkey|ref)*>
<!ELEMENT nkey (#PCDATA|ref)*>
<!ELEMENT nsub (#PCDATA|place|ref)*>

<!-- list, derived from html-->
<!ELEMENT list (head,(li|page)+)>
<!ELEMENT li (#PCDATA|page|ref|emph|br)*>
<!ATTLIST list id CDATA #REQUIRED>

<!-- in-text line break-->
<!ELEMENT br EMPTY>

<!-- new page tokens -->
<!ELEMENT page EMPTY>
<!ATTLIST page start CDATA #REQUIRED>
<!ATTLIST page pubid CDATA #IMPLIED>

<!-- CSP modern document references -->
<!ELEMENT mdr (#PCDATA)>
<!ATTLIST mdr id CDATA #REQUIRED>

<!-- depracted business directory -->
<!ELEMENT business (house,street,ward,occupier,trade, (staff*))>
<!ELEMENT house (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT ward (#PCDATA)>
<!ELEMENT occupier (#PCDATA)>
<!ELEMENT trade (#PCDATA)>
<!ELEMENT staff (#PCDATA)>

<!-- 1st generation dataset structure -->
<!ELEMENT geodata (geoclass+,geolocation+,geoitem+)>

<!ELEMENT geoclass (label,description,shortdesc,scale)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT description (#PCDATA|emph)*>
<!ELEMENT shortdesc (#PCDATA)>
<!ELEMENT scale (range)+>
<!ELEMENT range (#PCDATA)>

<!ATTLIST geoclass id ID #REQUIRED>
<!ATTLIST geoclass type (year|sterling) "year">
<!ATTLIST range id ID #REQUIRED>
<!ATTLIST range begin CDATA #REQUIRED>
<!ATTLIST range end CDATA #REQUIRED>

<!ELEMENT geolocation (#PCDATA)>
<!ATTLIST geolocation id ID #REQUIRED>
<!ATTLIST geolocation section CDATA #IMPLIED>
<!ATTLIST geolocation coordx CDATA #REQUIRED>
<!ATTLIST geolocation coordy CDATA #REQUIRED>

<!ELEMENT geoitem (#PCDATA)>
<!ATTLIST geoitem id ID #REQUIRED>
<!ATTLIST geoitem class IDREF #REQUIRED>
<!ATTLIST geoitem place IDREF #REQUIRED>



<!-- 2nd generation dataset structure -->
<!ELEMENT dataset (dsclass+,dsrecord+)>
<!ELEMENT dsclass (label,description,shortdesc?,scale?)>
<!ATTLIST dsclass id ID #REQUIRED>
<!ATTLIST dsclass type (year|sterling|text|integer|geox|geoy) "text">
<!ATTLIST dsclass sortkey CDATA #REQUIRED>
<!ATTLIST dsclass showheader (True|False) "True">
<!ATTLIST dsclass showcolumn (True|False) "True">
<!ATTLIST dsclass width CDATA #IMPLIED>
<!-- standard, that dsclass c0 in all cases should describe the main record -->
<!ELEMENT dsrecord (prop+)>
<!ATTLIST dsrecord id ID #REQUIRED>
<!ATTLIST dsrecord coordx CDATA #IMPLIED>
<!ATTLIST dsrecord coordy CDATA #IMPLIED>
<!ELEMENT prop (#PCDATA|ref|emph|br)*>
<!ATTLIST prop class IDREF #REQUIRED>



<!-- catalogue structure -->
<!ELEMENT catalogue (group+)>
<!ATTLIST catalogue classref CDATA #REQUIRED>
<!ELEMENT group (head,(item|group)*)>
<!ATTLIST group id ID #REQUIRED>
<!ELEMENT item (#PCDATA)>


<!-- END catalogue structure -->

<!-- mapset structure (OS) -->
<!ELEMENT mapset (eastingmin, eastingmax, northingmin, northingmax, eastingratio, northingratio, seriestitle, seriessub, county, mapsheet+, poi*)>
<!ELEMENT eastingmin (#PCDATA)>
<!ELEMENT eastingmax (#PCDATA)>
<!ELEMENT northingmin (#PCDATA)>
<!ELEMENT northingmax (#PCDATA)>
<!ELEMENT eastingratio (#PCDATA)>
<!ELEMENT northingratio (#PCDATA)>
<!ELEMENT seriestitle (#PCDATA)>
<!ELEMENT seriessub (#PCDATA)>
<!ELEMENT county (#PCDATA)>
<!ELEMENT mapsheet (tile, file, pubyear, swe, swn, nwe, nwn, nee, nen, see, sen)>
<!ATTLIST mapsheet id CDATA #REQUIRED>
<!ELEMENT tile (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT pubyear (#PCDATA)>
<!ELEMENT swe (#PCDATA)>
<!ELEMENT swn (#PCDATA)>
<!ELEMENT nwe (#PCDATA)>
<!ELEMENT nwn (#PCDATA)>
<!ELEMENT nee (#PCDATA)>
<!ELEMENT nen (#PCDATA)>
<!ELEMENT see (#PCDATA)>
<!ELEMENT sen (#PCDATA)>
<!ELEMENT poi (#PCDATA)>
<!ATTLIST poi easting CDATA #REQUIRED>
<!ATTLIST poi northing CDATA #REQUIRED>



<!-- entities -->
<!ENTITY % ent-isoamsa SYSTEM "isoamsa.ent">
%ent-isoamsa;
<!ENTITY % ent-isoamsb SYSTEM "isoamsb.ent">
%ent-isoamsb;
<!ENTITY % ent-isoamsc SYSTEM "isoamsc.ent">
%ent-isoamsc;
<!ENTITY % ent-isoamsn SYSTEM "isoamsn.ent">
%ent-isoamsn;
<!ENTITY % ent-isoamso SYSTEM "isoamso.ent">
%ent-isoamso;
<!ENTITY % ent-isoamsr SYSTEM "isoamsr.ent">
%ent-isoamsr;
<!ENTITY % ent-isobox SYSTEM "isobox.ent">
%ent-isobox;
<!ENTITY % ent-isocyr1 SYSTEM "isocyr1.ent">
%ent-isocyr1;
<!ENTITY % ent-isocyr2 SYSTEM "isocyr2.ent">
%ent-isocyr2;
<!ENTITY % ent-isodia SYSTEM "isodia.ent">
%ent-isodia;
<!ENTITY % ent-isogrk1 SYSTEM "isogrk1.ent">
%ent-isogrk1;
<!ENTITY % ent-isogrk2 SYSTEM "isogrk2.ent">
%ent-isogrk2;
<!ENTITY % ent-isogrk3 SYSTEM "isogrk3.ent">
%ent-isogrk3;
<!ENTITY % ent-isogrk4 SYSTEM "isogrk4.ent">
%ent-isogrk4;
<!ENTITY % ent-isolat1 SYSTEM "isolat1.ent">
%ent-isolat1;
<!ENTITY % ent-isolat2 SYSTEM "isolat2.ent">
%ent-isolat2;
<!ENTITY % ent-isonum SYSTEM "isonum.ent">
%ent-isonum;
<!ENTITY % ent-isopub SYSTEM "isopub.ent">
%ent-isopub;
<!ENTITY % ent-isotech SYSTEM "isotech.ent">
%ent-isotech;

<!ENTITY % ent-bhoa SYSTEM "bhoa.ent">
%ent-bhoa;

=== legislation/legislation-bho-to-clml/data/pubid-352/46276.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="46276" pubid="352" publish="true">
	<title>James the Second, 1685</title>
	<subtitle>Chapter IX. An Act to Enable His Majestie to make Grants Leases and Copies of Offices Lands and Hereditaments parcell of His
Highnesses Dutchy of Cornwall or annexed to the same and for Confirmation of Leases and Grants already made. [Rot. Parl. nu. 9.]</subtitle>
	<section id="s1">
		<head>Reciting that Tenants desire Renewal of Leases; and that Tenants may compound for Discharge of increased Rents.</head>
		<para id="p1">Whereas many of the Lands belonging to the Dutchy of Cornwall have beene granted by Lease to the
Tenants, some for the Terme of one two or three Lives and some for diverse yeares determinable upon one
two or three Lives and others for Thirty one yeares or under which Leases are desired to be renewed by many of the
said Tenants And whereas severall yeares next following after the happy Restauration of our late Soveraigne Lord
King Charles the Second of ever Blessed Memory diverse increased Rents were reserved as well upon the said Leased
Lands as upon many Copyhold Estates of the said Dutchy for the improvement of that Revenue whereof the Tenants
made complaint to his said late Majestie who was graciously pleased that they might Compound with his Officers for
the Discharge of the said increased Rents and be restored to the old Rents formerly paid for their respective
Tenements and Lands Now to the end the same may be accordingly effected and the said Tenants may be
encouraged to Renew their Leases and Estates and thereby the better enabled to Repaire their Houses and provide for
their Families and to improve their Lands holden of the said Dutchy</para>
		<section id="s2">
			<head>II. Grants of the Dutchy Lands made by the late King, or within Seven Years next ensuing, good in Law.</head>
			<para id="p2">Bee it Enacted by the Kings most Excellent Majestie by and with the Advice and Consent of the Lords Spirituall
and Temporall and the Commons in this present Parlyament Assembled and by the Authoritie of the same That all
Grants made in the time of his said late Majestie or to be made by Copy of Court-Roll according to the Custome of
the respective Mannour or Mannours of the said Dutchy or thereunto annexed or belonging and all Leases and Grants
soe made by his said late Majestie or made or to be made within Seven yeares next ensueing by Letters Patents or
Indentures under the Great Seale of England or Seale of the Court of Exchequer or by Copy of Court Roll according
to the Customs of the respective Mannours of any Offices Messuages Parks Lands Tenements or Hereditaments (other
then Honours Lordshipps, or Mannours) parcell of the Possessions of the said Dutchy of Cornwall or annexed to the
same shall be good and effectuall in Law according to the Purport and Contents of the same Copies Leases and Grants
against our said Soveraigne Lord the King his Heires and Successors and against all and every other person and persons
that shall at any time hereafter have inherit or enjoy the said Dutchy by force of any Act of Parlyament or by any
other Limitation whatsoever.</para>
		</section>
		<section id="s3">
			<head>III. Grant to be for no more than Three Lives or Thirty-one Years on the antient or most usual Rent.</head>
			<para id="p3">
				<emph type="i">Where no ancient Rent, then a reasonable Rent</emph>.</para>
			<para id="p4">Provided alwayes That every such Lease or Grant soe made or to be made be not made for more then One Two
or Three Lives or for Thirty one yeares or under or for some Terme of yeares determinable upon One Two or Three
Lives and not above And if such Leases or Grants be made in Reversion or Expectancy That then the same together
with the Estates in possession doe not exceede Three Lives or the Terme of Thirty one yeares and not in any wise
dispunishable of waste and soe as upon every such Lease shall be reserved the auntient or most usuall Rent or more or
such Rent as hath beene reserved yielded or paid for the same Lands for the greater part of Twenty yeares next before
the yeare of our Lord One thousand six hundred and sixtie and shall be reserved due or payable to him or her that
shall have the Inheritance or other Estate of the said Dutchy And where noe such Rent hath beene reserved or payable
That then upon every such Lease there shall be reserved a reasonable Rent not being under the Twentieth part of the
cleare yearely value of the Messuages Parks Lands Tenements or Hereditaments contained in such Lease and all
Leases and Grants otherwise made or to be made shall be null and void</para>
		</section>
		<section id="s4">
			<head>IV. Covenants, &amp;c. shall bind those in the Reversion.</head>
			<para id="p5">
				<emph type="i">General Saving, except for the King and Duke of Cornwall.</emph>
			</para>
			<para id="p6">And bee it further Ordained and Enacted by the Authoritie aforesaid That all Covenants Conditions Reservations
and other Agreements contained in every Lease Grant or Copy of Court Roll made or to be made as aforesaid shall be
good and effectuall in Law according to the Words and Contents of the same as well for and against them to whome.
the Reversion of the same Lands Tenements or Hereditaments shall come as for and against them to whome the Interest
of the said Leases Grants or Copies shall come respectively as if Our Soveraigne Lord the Kings Majestie at the time
of the makeing of such Covenants Conditions and Reservations and other Agreements were seized of an absolute
Estate in Fee-simple in the same Lands Tenements or Hereditaments Saveing alwayes to all and every Person and
Persons Bodies Pollitique and Corporate theire Heires and Successors Executors Administrators and Assignes
other then to Our said Soveraigne Lord the King and his Heires and the Duke and Dukes of Cornwall for the Time
being and his and their Heires and all and every person and persons that shall hereafter have Inherit or Enjoy the said
Dukedome of Cornwall by force of any Act of Parlyament or other Limitation whatsoever all such Rights Titles
Estates Customs Interests Tenures Claimes and Demands whatsoever of what nature kinde or quality soever of in to
or out of the said Offices Lands Tenements or Hereditaments or any of them as they or any of them had or ought to
have had before the makeing of this Act to all intents and purposes and in as large and ample manner and forme as
if this Act had never beene had or made This Act or any thing herein contained to the contrary notwithstanding.</para>
		</section>
		<section id="s5">
			<head>V. Tenants may compound with Treasury for taking off increased Rents within the next Seven Years.</head>
			<para id="p7">And bee it further enacted by the Authoritie aforesaid That in case any of the Lease-hold or Copyhold Tenants
of the said Dutchy shall at any time within Seven yeares next ensueing Compound or Agree with the Lord High
Treasurer of England or the Commissioners of the Treasury for the time being or with any such Person or Persons as
the Lord High Treasurer or Commissioners of the Treasury for the Time being shall Authorize Nominate and Appoint
for the takeing off and Dischargeing of any increased Rent reserved as aforesaid according to such Rules and Directions
as in that behalfe shall be given in Writeing under the Hands of the said Lord Treasurer or Commissioners of the
Treasury for the Time being Then upon such Composition soe made and the Money thereby ariseing duely paid
to the Receiver-Generall of the said Dutchy according to the Tenor and Contents of such Composition and Agreement
and accordingly Inrolled before the Auditor of the Premisses from thenceforth such Increased Rents shall cease and
become void and the Old Rent onely or such other Rent as in pursuance of this Act shall be Directed in or by such
Composition or Agreement shall be Charged upon all and every such Tenements Lands and other Hereditaments for
which such Composition Agreement Payment and Inrollment shall be soe made and none other Any Reservation
Condition or other Matter whatsoever to the contrary notwithstanding.</para>
		</section>
	</section>
</report>

=== legislation/legislation-bho-to-clml/data/pubid-352/46385.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE report SYSTEM "../dtd/report.dtd">
<report id="46385" pubid="352" publish="true">
	<title>William and Mary, 1692</title>
	<subtitle>Chapter XVI. An Act to prevent Fraud? by Clandestine Mortgages.</subtitle>
	<section id="s1">
		<head>Recital that Frauds are practised by necessitous Persons in borrowing Money.</head>
		<para id="p1">
			<emph type="i">Debtor upon Judgment, &#x0026;c. taking up Money of another upon Mortgage, without Notice of the Judgment to the Mortgagee, unless upon Notice by the Mortgagee he pay off the same within Six Months, shall lose his Equity to redeem; and Mortgagee may hold the Land against the said Mortgagor for such Estate as was granted to him</emph>.</para>
		<para id="p2">Whereas great Frauds and Deceits are too often practised by necessitous and evil disposed Persons in
borrowing of money and giving Judgments Statutes and Recognizances privately for securing the repayment
of the said money and the same persons do afterwards borrow money upon security of their Lands of other Persons
and do not acquaint the latter Lender thereof with the same whereby such late Lender is very often in danger to
lose his whole money or forced to pay of the Debts secured by the said Judgments Statutes and Recognizances
before they can have any benefitt of the said Mortgages. And whereas divers Persons do many times mortgage
their Lands more then once without giving notice of their first mortgage whereby Lenders of money vpon second
or after mortgages doe often lose their money and are put to great charges in suits and otherwise. For remedy
whereof and preventing the same as much as may be for the future Be it enacted by the King and Queens most
excellent Majesties by and with the advice and consent of the Lords Spiritual and Temporal and the Co[m]mons
in this present Parliament assembled and by the Authority of the same That if any Person or Persons from and
after the first day of May which shall be in the yeare of our Lord One thousand six hundred ninety and three
shall borrow any money or for any other valuable Consideration for the payment thereof voluntarily give acknowledge
permitt or suffer to be entred against him or them one or more Judgment or Judgments Statute or Statutes Recognizance
or Recognizances to any Person or Persons Creditor or Creditors And if the said Borrower or Borrowers Debter
or Debters shall afterwards take upp or borrow any other sum or sums of money of any other Person or Persons or for
other valuable Consideration become indebted to such Person or Persons and for secureing the repayment and discharge
thereof shall mortgage his her or their Lands or Tenements or any part thereof to the said second or other Lender
or Lenders of the said money Creditor or Creditors or to any other person or persons in trust for or to the use of
such second or other Lender or Lenders Creditor or Creditors and shall not give notice to the said Mortgagee
or Mortgagees of the said Judgment or Judgments Statute or Statutes Recognizance or Recognizances in writing
under his her or their Hand or Hands before the execution of the said Mortgage or Mortgages unlesse such
Mortgager or Mortgagers his her or their Heires vpon notice to him her or them given by the Mortgagee
or Mortgagees of the said Lands and Tenements his her or their Heirs Executors Administrators or Assigns in
writing vnder his her or their Hands and Seals attested by two or more sufficient witnesses of any such former
Judgment or Judgments Statute or Statutes Recognizance or Recognizances shall within Six months pay of and
discharge the said Judgment or Judgments Statute or Statutes Recognizance or Recognizanc[e]s and all Interest and
Charges due thereupon and cause or procure the same to be vacated or discharged by Record That then the
Mortgager or Mortgagers of the said Lands and Tenements his her or their Heires Executors Administrators or
Assigns shall have no benefitt or remedy against the said Mortgagee or Mortgagees his her or their Heires
Executors Administrators or Assigns or any of them in Equity or elsewhere for redemption of the said Lands
and Tenements or any part thereof But the said Mortgagee or Mortgagees his her or their Heirs Executors
Administrators and Assigns shall and may hold and enjoy the said Lands and Tenements for such Estate and
Term therein as were or was granted and settled to the said Mortgagee or Mortgagees against the said Mortgager
or Mortgagers and [and<ref idref="n1">1</ref>] all Person or Persons lawfully claiming from by or vnder him her or them freed from Equity
of Redemption and as fully to all intents and purposes whatsoever as if the same had been purchased absolutely
and without any power or liberty of Redemption</para>
	</section>
	<section id="s2">
		<head>II. Persons having mortgaged and mortgaging again without Notice to the Second or other succeeding Mortgagee, to lose his Equity of Redemption.</head>
		<para id="p3">And be it further enacted by the Authority aforesaid That if any Person or Persons who have or hath once
mortgaged or from and after the said First day of May shall mortgage any Lands or Tenements to any Person
or Persons for Security of Money lent or otherwise accrued or become due or for other valuable Considerations
And if the said [Mortgager<ref idref="n2">2</ref>] or [Mortgagers<ref idref="n3">3</ref>] shall again mortgage the same Lands or Tenements or any part thereof
to any other Person or Persons for valuable Considerations (the said former Mortgage being in force and not
discharged) and shall not discover to the said second or other Mortgagee or Mortgagees or some or one of them
the former Mortgage or Mortgages in writing under his or their Hands That then and in those cases also the
said [Mortgager<ref idref="n2">2</ref>] or [Mortgagers<ref idref="n3">3</ref>] his her or their Heires Executors Administrators or Assigns shall have no Relief or
Equity of Redemption against the said second or after Mortgagee or Mortgagees his her or their Heirs Executors
Administrators or Assignes upon the said after mortgage or mortgages but that such Mortgagee or Mortgagees his (<ref idref="n4">4</ref>) or
their Heirs Executors Administrators and Assigns shall and may hold and enjoy such more then once mortgaged Lands
and Tenements for such Estate and Terme therein as were or was granted and conveyed by the said [Mortgager<ref idref="n2">2</ref>]
or [Mortgagers<ref idref="n3">3</ref>] against him her or them his her or their Heires Executors or Administrators respectively freed
from Equity of Redemption and as fully to all intents and purposes as if the same had been and absolute purchase
and without any power or liberty of Redemption.</para>
	</section>
	<section id="s3">
		<head>III. Under-Mortgagees may redeem.</head>
		<para id="p4">Provided always and be it further enacted by the Authority aforesaid That neverthelesse if it so happen there
be more then one Mortgage att the same time made by any Person or Persons to any Person or Persons of the
same Lands and Tenements the several late or under Mortgagees his her or their Heirs Executors Administrators
or Assigns shall have power to redeem any former Mortgage or Mortgages upon payment of the principal Debt
Interest and Costs of Suit to the prior Mortgagee or Mortgagees his her or their Heires Executors Administrators
or Assigns any thing herein contained to the contrary thereof in any wise notwithstanding.</para>
	</section>
	<section id="s4">
		<head>IV. Proviso for Dower.</head>
		<para id="p5">Provided always that nothing in this Act contained shall be construed deemed or extended to bar any Widow
of any [Mortgager<ref idref="n2">2</ref>] of Lands or Tenements from her Dower and Right in or to the said Lands who did not
legally join with her Husband in such Mortgage or otherwise lawfully bar or exclude her selfe from such her
Dower or Right.</para>
		<note id="n1" number="1">1<emph type="i">O</emph>. omits.</note>
		<note id="n2" number="2">Mortgagor <emph type="i">O</emph>.</note>
		<note id="n3" number="3">Mortgagors <emph type="i">O</emph>.</note>
		<note id="n4" number="4">her <emph type="i">O</emph>.</note>
	</section>
</report>
